### ISSUE TITLE
应用审核列表中的审核结果(状态)需要把审核角色名给加上吗？

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#1019]
@imdonkey ，目前有ISV审核，商务审核，技术审核。目前的审核结果(状态)都统一成了“审核中”，“已拒绝”， “已通过”来显示的，需要在前面加上ISV/商务/技术吗？

<img width="1100" alt="图片" src="https://user-images.githubusercontent.com/38676269/55050238-99598300-508a-11e9-8195-44f5b58343ae.png">

**Comment by imdonkey** [comment]
不需要，对于开发者来说不需要知道审核的具体环节。另外这个环节也有可能有变化，严格来说是根据审核模板来的。

**Comment by whDongRui** [comment]
好的。但这个地方的列表是给审核人员看的，一般开发人员是看不到的。那我先把这个issue关掉吧。
