### ISSUE TITLE
全部应用目前只能看到已上架或已下架的应用

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1020]
![Screenshot from 2019-03-27 12-21-58](https://user-images.githubusercontent.com/5917832/55050308-f0f7ee80-508a-11e9-979e-f06edf860773.png)

应用审核只能看到提交审核的版本。 
开发中未提交审核的版本，目前无法看到，包括部署的实例，配置包等等，担心如果开发者遇到问题，管理员没办法协助。

**Comment by imdonkey** [comment]
这个问题下个版本我考虑下吧，目前在应用审核模块中只能看提交上来的应用是合理的，至于开发过程中遇到的问题应该有其他方式来解决。

**Comment by whDongRui** [comment]
目前讨论的结果是暂时不修改，下一版本再做优化。我先关掉了。
