### ISSUE TITLE
管理员技术审核部署测试，应该固定审核版本

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1021]
![Screenshot from 2019-03-27 12-27-57](https://user-images.githubusercontent.com/5917832/55050460-d07c6400-508b-11e9-9589-c76655cf68d8.png)
如果当前应用有多个交付模式，多个版本， 进行部署测试时，不知道开发者提交审核的是哪个版本。

**Comment by whDongRui** [comment]
目前部署那会的url一般会有versionId，比如说下面截图中我是从“审核详情--配置文件”中的部署测试的链接跳转守来的，已经固定了了审核版本 。但也可以切换成其它交付类型或版本来测试。


<img width="1204" alt="图片" src="https://user-images.githubusercontent.com/38676269/55057052-024cf500-50a3-11e9-8477-22cbe1ef6719.png">

**Comment by whDongRui** [comment]
目前就是技术审核那个“测试部署”的按钮没有传versionId，现在已经修改了，修复代码请参见[PR](#1027)。
