### ISSUE TITLE
管理员技术审核，部署测试点击创建后跳转不对

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1022]
![Screenshot from 2019-03-27 12-29-27](https://user-images.githubusercontent.com/5917832/55050503-09b4d400-508c-11e9-891b-70fd8ceecf9c.png)
跳转到了 管理员的应用中心， 应该是跳转到测试实例的页面。

**Comment by whDongRui** [comment]
目前ISV,Dev部署测试实例的会跳转到对应app的沙盒实例页面，
Admin会跳转到管理理的测试实例页面，
User portal页面的部署都会跳转到User portal下的我的实例页面。
修复代码请参见[PR](#1027)。
