### ISSUE TITLE
管理员测试实例 代理 调用接口不对

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1023]
![Screenshot from 2019-03-27 12-33-29](https://user-images.githubusercontent.com/5917832/55050629-995a8280-508c-11e9-9332-151136d24229.png)
应该用debug

**Comment by whDongRui** [comment]
这个地方的逻辑已经优化了。目前管理员测试实例 代理 调用接口为debug_clusters，修复代码请参见[PR](#1027)。

<img width="1283" alt="图片" src="https://user-images.githubusercontent.com/38676269/55060466-7dff6f80-50ac-11e9-9eb4-4abb12c38ff5.png">
