### ISSUE TITLE
分类 无法看到 ”未分类“， 在最下面，需要缩小浏览器才能看到。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1035]
![Screenshot from 2019-03-28 10-01-20](https://user-images.githubusercontent.com/5917832/55124232-83a69500-5140-11e9-869b-0cc99fc99269.png)

**Comment by liiil825** [comment]
这里只能让左边的滚动条改为和右边连动了(`position:sticky `)，不然把左边高度少个左边的高度，一开始无法被感知到
