### ISSUE TITLE
ssh key 页面，点击解绑所有节点，没反应

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1037]
![Screenshot from 2019-03-28 10-05-22](https://user-images.githubusercontent.com/5917832/55124388-06c7eb00-5141-11e9-8f7b-46cd3bc841c5.png)

**Comment by whDongRui** [comment]
这一个地方的判断逻辑有一个问题，已经修复了。绑定的节点数为0个，下拉菜单中应该没有“解绑SSH密钥”

<img width="1214" alt="图片" src="https://user-images.githubusercontent.com/38676269/55127127-0a13a480-514a-11e9-98df-d390afbceb60.png">
