### ISSUE TITLE
先隐藏已暂停，已销毁  

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1038]
![Screenshot from 2019-03-28 10-09-13](https://user-images.githubusercontent.com/5917832/55124562-979ec680-5141-11e9-9f2d-ea2e45456233.png)

**Comment by whDongRui** [comment]
@chilianyi 这个地方可以把过滤弹层中的“已关闭”，“已暂停”可去掉，但列表默认查询的过滤状态中还要包含这两个状态？是这样的吗？

**Comment by whDongRui** [comment]
已经隐藏了，修复代码请参见[PR](#1066)。

<img width="1214" alt="图片" src="https://user-images.githubusercontent.com/38676269/55135326-4ead3900-5166-11e9-86a3-42af12a5db98.png">
