### ISSUE TITLE
状态切换到的等待中，强制刷新也不会回来。但界面没有显示这个过滤条件

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1040]
![Screenshot from 2019-03-28 10-17-48](https://user-images.githubusercontent.com/5917832/55124872-c2d5e580-5142-11e9-8774-2e24dec2274b.png)

**Comment by chilianyi** [comment]
这种情况下，切换到 ”已部署应用“ 页面，也看不到信息了。 其实应该是有部署的集群的。
![Screenshot from 2019-03-28 10-19-35](https://user-images.githubusercontent.com/5917832/55124951-12b4ac80-5143-11e9-82a2-34ce74a2329f.png)

”已部署应用“页面强制刷新下可以看到
![Screenshot from 2019-03-28 10-20-19](https://user-images.githubusercontent.com/5917832/55124961-219b5f00-5143-11e9-85e3-eafb149b08dd.png)

**Comment by whDongRui** [comment]
状态切换到的等待中，强制刷新也不会回来，是因为过滤时把状态同步到url上去了。
在”我的实例“页面过滤状态后，切换到 ”已部署应用“ 页面，能看到信息了, 修复代码请参见[PR](#1066)。

<img width="1275" alt="图片" src="https://user-images.githubusercontent.com/38676269/55135493-c4b1a000-5166-11e9-824d-d6fd263ea829.png">
