### ISSUE TITLE
左侧显示3个app， 右侧显示2个app， 查看发现其中有一个是deleted状态。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1041]
![Screenshot from 2019-03-28 10-23-35](https://user-images.githubusercontent.com/5917832/55125090-953d6c00-5143-11e9-81e1-7816132b4dab.png)

**Comment by whDongRui** [comment]
这个其它人把这个app除非掉了，你自己的账号之前浏览过也会有记录,
还有不同浏览器，不同设备都会造成应用删除了应用，但左侧导航还会显示这个app，
这个问题最好的解决方法只能是后端能存最近浏览的app，然后前端调接口去查出来。

**Comment by chilianyi** [comment]
这个最近浏览app，能过滤下已删除的吗

**Comment by whDongRui** [comment]
每次isv或dev登录时获取本地localstorage中的app信息，现去查询一次，发现已经删除了就更新一下localstorage中的信息。

**Comment by whDongRui** [comment]
这个已经改了，现在进入开发者视图，会用localstorage中的app信息的id再去查询一次来同步最新的数据，修复代码请参见[PR](#1066)。

<img width="1113" alt="图片" src="https://user-images.githubusercontent.com/38676269/55137050-e7de4e80-516a-11e9-9a00-135a36a87593.png">
