### ISSUE TITLE
服务商 审核，其实也有技术审核的成分，应该也加个可以测试部署的入口

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1047]
![Screenshot from 2019-03-28 11-19-21](https://user-images.githubusercontent.com/5917832/55127528-69be7f80-514b-11e9-88fc-012c215c2b9a.png)

**Comment by whDongRui** [comment]
目前修改成ISV审核和技术审核，都有“部署测试”的按钮入口。

<img width="1184" alt="图片" src="https://user-images.githubusercontent.com/38676269/55129504-56fb7900-5152-11e9-842f-bb9f8ccfe9b9.png">
