### ISSUE TITLE
查看详细标准 链接不对。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1048]
![Screenshot from 2019-03-28 11-23-25](https://user-images.githubusercontent.com/5917832/55127669-ee110280-514b-11e9-8634-3135f774ab9d.png)

**Comment by whDongRui** [comment]
这个刚才讨论过了，没这个个链接，暂时先去掉这个链接。修复代码请参见PR #1066

<img width="823" alt="图片" src="https://user-images.githubusercontent.com/38676269/55155761-2982ef80-5193-11e9-8db4-f6751c3a8ee4.png">
