### ISSUE TITLE
开发者这里，是不是应该是”测试部署“ ， 包括后面的部署页面。 因为这个部署到了沙盒。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1051]
![Screenshot from 2019-03-28 12-42-07](https://user-images.githubusercontent.com/5917832/55130739-ee62cb00-5156-11e9-91d9-17295a1a492c.png)
![Screenshot from 2019-03-28 12-43-03](https://user-images.githubusercontent.com/5917832/55130758-0aff0300-5157-11e9-9e4a-f71e264136c4.png)

**Comment by whDongRui** [comment]
操作弹层中的的名称已经改成”部署测试“，
另外点进出的部署页面的标题已经改成了”部署测试实例“，下面的提示文字也作了相应的调整。
修复代码请参见[PR](#1066)。

<img width="1340" alt="图片" src="https://user-images.githubusercontent.com/38676269/55138760-2b3abc00-516f-11e9-8619-62726d5be4a3.png">

<img width="1366" alt="图片" src="https://user-images.githubusercontent.com/38676269/55138718-1a8a4600-516f-11e9-9317-daee8898c286.png">
