### ISSUE TITLE
沙盒 里点击实例，进入实例详情，但左侧第二排菜单不见了。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1053]
![Screenshot from 2019-03-28 13-29-06](https://user-images.githubusercontent.com/5917832/55132484-84015900-515d-11e9-9e26-796c241d733e.png)
![Screenshot from 2019-03-28 13-29-56](https://user-images.githubusercontent.com/5917832/55132499-967b9280-515d-11e9-83ac-47a7958eea4e.png)

**Comment by whDongRui** [comment]
实例详情页面，或者其它列表进入的详情页面(或者说页面标题前有返回图标的)都是没有二级导航的。
如下截图，设计也是这样设计的。

<img width="836" alt="图片" src="https://user-images.githubusercontent.com/38676269/55133023-3c7bcc80-515f-11e9-8464-63ef91467a62.png">

**Comment by chilianyi** [comment]
这个页面想查看所有测试集群，就不知道如何操作了。
