### ISSUE TITLE
点击左上角”服务商中心“前面的PI，也是进入应用中心，这个是预期的吗

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1054]
![Screenshot from 2019-03-28 13-31-54](https://user-images.githubusercontent.com/5917832/55132584-e0fd0f00-515d-11e9-9696-7d0f35630128.png)

**Comment by whDongRui** [comment]
应该是是这样的吧，这个可以问一下产品或设计 。不过“”服务商中心“这文字应该可以点击跳转的，我一会加上。

**Comment by imdonkey** [comment]
portal 里左上角的 logo 只是用来回到 portal 本身的首页就好，不需要跳出到“应用中心”。

**Comment by whDongRui** [comment]
好的，已经改成回到 portal 本身的首页，并且文字也可以点击跳转。修复代码请参见[PR](#1066)。

<img width="616" alt="图片" src="https://user-images.githubusercontent.com/38676269/55137828-f3cb1000-516c-11e9-8e9b-de3a5d32284f.png">
