### ISSUE TITLE
沙盒实例这里可以加个代理 tab页吗

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1055]
![Screenshot from 2019-03-28 13-35-01](https://user-images.githubusercontent.com/5917832/55132730-4e10a480-515e-11e9-8899-161c1db2df25.png)

**Comment by whDongRui** [comment]
目前沙盒实例，用户实例都给加了，如下截图。修复代码请参见PR #1066

<img width="1329" alt="图片" src="https://user-images.githubusercontent.com/38676269/55155890-75ce2f80-5193-11e9-86da-78eb9067e0f7.png">
