### ISSUE TITLE
应用审核，已处理显示30，点击下一页变成1w多

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1058]
![Screenshot from 2019-03-28 13-43-49](https://user-images.githubusercontent.com/5917832/55133131-8a90d000-515f-11e9-9ef1-1c6589edb9cf.png)
![Screenshot from 2019-03-28 13-44-28](https://user-images.githubusercontent.com/5917832/55133157-9f6d6380-515f-11e9-9d03-e1a0f6411b35.png)

**Comment by whDongRui** [comment]
这个地方的分页查询方法调用错了，我刚改了，下面截图是第二页，总数还是30条。修复代码请参见[PR](#1066)。

<img width="1332" alt="图片" src="https://user-images.githubusercontent.com/38676269/55135144-c2027b00-5165-11e9-920b-97549f5e1a7b.png">
