### ISSUE TITLE
点击已处理的某一条，进去以后点击返回，默认进入了未处理

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1059]
![Screenshot from 2019-03-28 13-48-12](https://user-images.githubusercontent.com/5917832/55133289-26bad700-5160-11e9-8381-e75083c8214d.png)
![Screenshot from 2019-03-28 13-48-54](https://user-images.githubusercontent.com/5917832/55133318-3e925b00-5160-11e9-9fec-a1c432cb163d.png)

包括里面的”应用信息“的链接

**Comment by chilianyi** [comment]
同 入驻申请这里
![Screenshot from 2019-03-28 13-51-49](https://user-images.githubusercontent.com/5917832/55133444-acd71d80-5160-11e9-895d-12ec6bdfcb34.png)

**Comment by chilianyi** [comment]
同 实例这里
![Screenshot from 2019-03-28 14-21-37](https://user-images.githubusercontent.com/5917832/55134815-dabe6100-5164-11e9-9e9f-9a64e34d71bd.png)

**Comment by whDongRui** [comment]
这个已经修复了， 应用审核和入驻申请列表中点击table上面的类型会同步更新到浏览器上的url，这个进入详情再返回就返回之前选择类型下面的table数据了。实例列表，代里点不进详情页面，所以不用修复。
修复代码请参见PR #1083

<img width="1312" alt="图片" src="https://user-images.githubusercontent.com/38676269/55209466-ae1a5000-521d-11e9-921d-a84101ab93a4.png">

<img width="1306" alt="图片" src="https://user-images.githubusercontent.com/38676269/55209477-c1c5b680-521d-11e9-8a2b-f89e1cc0b8da.png">
