### ISSUE TITLE
右侧的"审核人员" 这个列名是不是不准确， 里面其实是开始审核的动作。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1060]
![Screenshot from 2019-03-28 13-56-54](https://user-images.githubusercontent.com/5917832/55133657-60d8a880-5161-11e9-86fe-24a2cd4bc1f5.png)

**Comment by whDongRui** [comment]
这一列的列名可以改成”操作“

**Comment by chilianyi** [comment]
嗯，是的。

**Comment by whDongRui** [comment]
修复代码请参见[PR](#1066)。
