### ISSUE TITLE
管理员修改其他用户的密码，这个是不是应该隐藏下比较好。

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1062]
![Screenshot from 2019-03-28 14-00-57](https://user-images.githubusercontent.com/5917832/55133839-efe5c080-5161-11e9-8e50-28e6f6e538a2.png)

**Comment by chilianyi** [comment]
![Screenshot from 2019-03-28 14-02-08](https://user-images.githubusercontent.com/5917832/55133876-1a377e00-5162-11e9-9533-fac4a221ad01.png)
对于普通用户和应用服务商， 应该只能”编辑信息“， 其他的都隐藏。

**Comment by whDongRui** [comment]
目前没有重置密码的功能，这个地方如果其它用户忘记了密码，有这个入口管理员可以重新设置一个密码给用户。

**Comment by chilianyi** [comment]
嗯，那就保留修改密码和编辑信息，其他的应该不需要

**Comment by liiil825** [comment]
> ![Screenshot from 2019-03-28 14-02-08](https://user-images.githubusercontent.com/5917832/55133876-1a377e00-5162-11e9-9533-fac4a221ad01.png)
> 对于平台用户，普通用户和应用服务商， 应该只能”编辑信息“， 其他的都隐藏。

这页面只有管理员的才可见啊

**Comment by liiil825** [comment]
ok
