### ISSUE TITLE
测试实例这里没有展示出”环境信息“

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1065]
![Screenshot from 2019-03-28 14-19-22](https://user-images.githubusercontent.com/5917832/55134697-80bd9b80-5164-11e9-865e-0121f58632b6.png)

**Comment by whDongRui** [comment]
这个admin登录的吗？我这边用admin的账号登录是能显示测试环境的。

<img width="1348" alt="图片" src="https://user-images.githubusercontent.com/38676269/55136117-7c937d00-5168-11e9-9b2f-ea9f2a51f1b2.png">

**Comment by chilianyi** [comment]
isv 用户登录的

**Comment by whDongRui** [comment]
@chilianyi ，isv登录看不你截图中的页面啊，只能通过开发者的视图看“用户实例”或“沙盒实例”的页面。

<img width="1024" alt="图片" src="https://user-images.githubusercontent.com/38676269/55140174-6b4f6e00-5172-11e9-8d24-36b8e5f6bc69.png">
