### ISSUE TITLE
测试实例 代理 用错了api

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1067]
![Screenshot from 2019-03-28 14-28-46](https://user-images.githubusercontent.com/5917832/55135164-d8a8d200-5165-11e9-8e93-7d6cd45ad0bc.png)
需要用debug_cluster 的api

**Comment by chilianyi** [comment]
代理 可以没有版本这列。

**Comment by whDongRui** [comment]
这个昨天我已经改成了debug_cluster 的api，应该是单机环境没及时更新吧。
