### ISSUE TITLE
被拒绝的，提交审核，右侧没有自动刷新

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1069]
![Screenshot from 2019-03-28 15-19-46](https://user-images.githubusercontent.com/5917832/55137840-fe85a500-516c-11e9-8972-8bac460a4196.png)

**Comment by whDongRui** [comment]
刚刚已经加了提交审核后，又去重新请求了审核记录的接口，目前最新记录能自动刷新。修复代码请参见[PR](#1066)。

<img width="1329" alt="图片" src="https://user-images.githubusercontent.com/38676269/55139898-d0569400-5171-11e9-8eed-9d486a775ae8.png">
