### ISSUE TITLE
这个node id 写死了

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#1071]
![Screenshot from 2019-03-28 16-45-03](https://user-images.githubusercontent.com/5917832/55143044-e0be3d00-5178-11e9-95f3-6b7c0d84036f.png)

**Comment by whDongRui** [comment]
这个是因为如果不传0的话，传空数组[]或“”的话，会查出所有的nodes.

**Comment by whDongRui** [comment]
这个页面查询nodes有时传了一个“0”去查询，是为了查询密钥对应的节点数据，当密钥中的数据没有节点id或为“”时就传了一个“0”去查询，有节点id就会传对应的节点id去查询。

因为不去查询的话，左侧的密钥可以相互切换，有可能上一个密钥查询出有节点数据，如果不去查询的话右侧列表数据就会有问题，可能是上个密钥对应的节点数据。
