### ISSUE TITLE
根据设置权限显示导航菜单和操作按钮

### ISSUE THREAD

**Issue by liiil825** [openpitrix/dashboard#1085]
- [x] 导航菜单
- [x] 操作按钮

**Comment by whDongRui** [comment]
action-id.js的配置key，vaule都是一样的感觉没必要，建议可以改进一下，把navMap.js中的actionId中的值放在action-id.js这个文件中来配置。
navMap.js中actionId永远只取一个值，后面控制菜单如果增加或减少一个id来判断，只用改动action-id.js配置中key对应的value就可以了。

```
// action-id.js配置改成这样：
app_reviews: [ 'technical_review', 'business_review']
// 再把navMap.js中的配置改成这样
actionId: ACTION.app_reviews
```

**Comment by liiil825** [comment]
> action-id.js的配置key，vaule都是一样的感觉没必要，建议可以改进一下，把navMap.js中的actionId中的值放在action-id.js这个文件中来配置。
> navMap.js中actionId永远只取一个值，后面控制菜单如果增加或减少一个id来判断，只用改动action-id.js配置中key对应的value就可以了。
> 
> ```
> // action-id.js配置改成这样：
> app_reviews: [ 'technical_review', 'business_review']
> // 再把navMap.js中的配置改成这样
> actionId: ACTION.app_reviews
> ```

嗯，可以
