### ISSUE TITLE
新添加的用户无法删除？

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#1126]
新建的部门下，添加的用户无法删除，普通用户和 ISV 用户也没有看到删除选项
![image](https://user-images.githubusercontent.com/40452856/59476739-b715d780-8e84-11e9-9f1c-8743fbb3c7db.png)
![image](https://user-images.githubusercontent.com/40452856/59476814-0f4cd980-8e85-11e9-94e8-e7b3fe7d60cd.png)

同样，在 ISV 登录后的用户列表也没有看到删除用户的选项。
![image](https://user-images.githubusercontent.com/40452856/59481078-7ffbf200-8e95-11e9-918d-835a22fb6f4d.png)

**Comment by liiil825** [comment]
这个先后端不允许删除，需要后端支持

**Comment by iwisunny** [comment]
可以关掉这个issue了？
