### ISSUE TITLE
在 ISV 的账号下新建的角色权限规则与实际不相符

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#1127]
在 ISV 的账号下新建了一个测试角色，如下只给他创建测试环境的权限，并未开启创建应用相关的权限
![image](https://user-images.githubusercontent.com/40452856/59477480-eaa63100-8e87-11e9-8711-38329ece14c8.png)

但是该角色的用户登录后，还可以创建和上传应用，这个似乎与设置的规则不相符。
![image](https://user-images.githubusercontent.com/40452856/59477555-3bb62500-8e88-11e9-9e45-5584d9afe2f2.png)

**Comment by liiil825** [comment]
这个问题比较复杂。
1. 当前的设计是对每一个 `action` 的操作权限，设置后传给后端，然后把权限保持到了数据库，当用户操作时由后端控制是否有权限执行这个 `action`。
2. 前端页面现在导航栏，设计是按照角色来展示的，开发者设计时就是这样的，如果没有这个，应该展示哪些导航栏，这个可能需要重新讨论、设计下。
3. 现在前端已经按照权限对部分导航进行了隐藏。包括以下这些：

**管理员的导航以下会受到权限影响隐藏：（原则是可能需要的操作需要全部关闭才会隐藏）**
- 用户与权限
- 平台设置
- 应用审核
- 应用分类
- 应用服务商

**应用服务商的导航以下会受到权限影响隐藏**
- 团队成员
- 应用审核


现在能做到的权限控制前端展示还很不完善，如果真的需要再进一步，得一起讨论下才行

**Comment by liiil825** [comment]
@wangxhsoft @FeynmanZhou @iwisunny

**Comment by iwisunny** [comment]
@liiil825  目前能否做到根据已启用的action 去判断是否展示页面的某个功能块？某个功能块（比如创建应用）应该包含了若干action，反过来 知道了启用的action 就可以判断是否隐藏这个功能块吧
