### ISSUE TITLE
应用的审核状态不一致

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#1128]
应用的审核状态不一致，如下所示：
![image](https://user-images.githubusercontent.com/40452856/59563956-45e84700-9073-11e9-992d-4450ed2ea398.png)

**Comment by iwisunny** [comment]
@whDongRui 跟进下这个问题

**Comment by whDongRui** [comment]
左侧导航栏的状态是app的状态，app应该没有的审核中的状态，在没有正式发布版本之前都是“待提交”的状态。右边页面的状态是version的状态，它的状态多一些，会随着操作而变化。

这个应该没问题，你可以发布上加一个版本后看左侧导航栏中app的状态有变化不？
