### ISSUE TITLE
UI 经常性地报 “没有权限”

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#1129]
UI 经常性地报 “没有权限”，虽然不影响正常使用，但容易给用户造成困惑。
![image](https://user-images.githubusercontent.com/40452856/59574057-5e467900-90e8-11e9-8b45-c00aad9b5736.png)

console 也有报错，环境私发。
![image](https://user-images.githubusercontent.com/40452856/59574104-8e8e1780-90e8-11e9-933a-2541a1ec312a.png)

**Comment by iwisunny** [comment]
报没有权限可能是iam服务或者api server导致的，console的报错时 ws server变更了。我来修复
