### ISSUE TITLE
应用部署至 Aliyun 和 QingCloud，k8s 后，主机和硬盘都成功创建，但节点状态一直是更新中

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#1130]
应用部署至 Aliyun 、k8s 和 QingCloud 后，主机和硬盘都成功创建，但节点状态一直是更新中 (环境私发)

QingCloud
![image](https://user-images.githubusercontent.com/40452856/59656074-0f274380-91cf-11e9-81b7-8102413f2653.png)

K8s
![image](https://user-images.githubusercontent.com/40452856/59656130-3aaa2e00-91cf-11e9-8f26-a2a91672f475.png)

Aliyun
![image](https://user-images.githubusercontent.com/40452856/59656180-5ca3b080-91cf-11e9-9263-39433e78572a.png)

**Comment by iwisunny** [comment]
这个是后端问题，状态是通过websocket来更新的

**Comment by iwisunny** [comment]
@pengcong06 跟进下这个问题吧
