### ISSUE TITLE
bug list

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#121]
1.  clusters 、repos query parameters  has no filtering results
2. deploy app result  has no app_id
3. repo、runtime edit page data loss after refresh
4. runtime edit page modify zone field no effect  after save
5. delete app version no effect

**Comment by iwisunny** [comment]
meeting 2018-6-29
---

- [ ] 更换Logo
- [ ] app设计要提供默认icon
- [ ] App detail, deploy app不要二级导航tabs
- [ ] more不加粗
- [ ] 列表中name中不加description，加id
- [ ] Cluster 列表admin不能删除集群, pending状态可以删除
- [ ] Cluster 增加启用停用stop,start(详情页页面也要加对应的操作）
- [ ] Node 列表要加node id，不要app version字段
- [ ] 列表增加批量删除（cluster ）
- [ ] Cluster detail 要显示集群id(后端有数据时)
- [ ] Runtime, repo编辑页面有些内容能改：name ,description, labels, Key ID显示***号
- [ ] 列表数据要传status数组筛选（不显示deleted）
- [ ] 表头status增加过滤图标，可筛选deleted
- [ ] runtime列表cluster count要用后端接口查询
- [ ] 列表中Update日期要显示时间，分两行显示
- [ ] repo编辑页Provider, url不能修改
- [ ] category编辑页面中增加description字段
- [ ] App 列表visibility字段继承repo中的数据，通过接口传多个app_id查询
- [ ] Overview和列表中id增加复制
- [ ] 二级导航要固定顶部
- [ ] repo里面查看runtime的时候, 需要传repo的selector参数, 传到 label下.
- [ ] cluster的 job状态未动态更新

**Comment by iwisunny** [comment]
done.
