### ISSUE TITLE
集群获取状态数据不正确

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#369]
1：QingCloud集群状态数据创建，需要大约10分钟同步
2：获取硬盘数据不正确
<img width="1352" alt="default" src="https://user-images.githubusercontent.com/5114179/45859057-f3ebec80-bd92-11e8-9690-e70a7cf2a168.png">

**Comment by iwisunny** [comment]
- 状态同步那个是websocket消息推送，有时socket会断开，导致状态不一致。手动点刷新按钮会主动获取状态，长时间在更新，就是后端问题了
- 获取硬盘数据不正确是前端Bug， 已解决

**Comment by iwisunny** [comment]
@chilianyi 状态更新需要很长时间
