### ISSUE TITLE
应用显示状态

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#370]
step1：ISV开放ZK应用，对应2个版本，0.1和0.2
step2：0.1 未提交审核 0.2 审核通过没有发布
step3：normal 用户登陆可看到zk应用，并且2个版本都可以部署
<img width="1338" alt="3" src="https://user-images.githubusercontent.com/5114179/45859248-de2af700-bd93-11e8-9a70-b945034a9953.png">
<img width="1188" alt="2" src="https://user-images.githubusercontent.com/5114179/45859249-de2af700-bd93-11e8-9cd3-5bcdffac2e45.png">

**Comment by iwisunny** [comment]
只要保证app version的状态值是正确的，剩下的问题就是前端过滤的Bug
