### ISSUE TITLE
应用状态与逻辑

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#373]
1：admin登陆，全部应用中，状态为待提交、已上线、已下架、已删除
2：在应用列表中，按状态筛选，在无数据的情况下，无法返回
3：ISV登陆，目前应用可随便删除，应用可删除、可暂停的前提：
       1：所有 version 都是 suspended/delete 的话, app就变成 suspended
      2：所有version都是 deleted的话, app就变成 deleted
<img width="1429" alt="4" src="https://user-images.githubusercontent.com/5114179/45861880-ba6ead80-bda1-11e8-961d-7bb98f86c57c.png">
<img width="991" alt="5" src="https://user-images.githubusercontent.com/5114179/45861881-ba6ead80-bda1-11e8-82fe-b09cad0bf2ea.png">
<img width="1017" alt="7" src="https://user-images.githubusercontent.com/5114179/45861882-ba6ead80-bda1-11e8-9b82-e5a32f3ed8b9.png">

**Comment by whDongRui** [comment]
这个前端状态显示已经加了mappingStatus这个方法在控制了。删除app的逻辑已经修复，关于verion的状态改变了要变app的状态，这个是后端接口中在控制 。
