### ISSUE TITLE
文案修改建议

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#379]
建议这里的文案修改为“选择分类”，因为这里是将应用添加到分类中。并且分类的管理页面也有个修改分类，但是是修改分类的名称和描述信息。所以建议区别一下，避免用户误解。
![image](https://user-images.githubusercontent.com/40452856/45923818-e06f8b80-bf22-11e8-92a6-ece055918b7a.png)

另外，Dashboard 翻译成 “总览” 更合适一些吧。直译成仪表盘感觉略奇怪。

**Comment by iwisunny** [comment]
ok
