### ISSUE TITLE
【设计】Dashboard 样式问题

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#389]
- [x] "More..." 的颜色是 N300 , hover 等状态的颜色和 zpl://screen?pid=5a422c2577a4a73371c92c01&sid=5b4c4133729e51c20898f0f3 保持一致。
- [x] "dev" 和 "admin" 界面右侧的 grid 间隔应该是 20px, “normal” 界面的 grid 间隔还是 20px 保持不变。具体设计参看 zpl://screen?pid=5a422c2577a4a73371c92c01&sid=5b8fbb0fbb23ec47815ac968
- [x] breadcrumb 应该除了最后一级，其他都是可点击的
- [x] Dashboard 的菜单名称应该是 overview, 目前有两个 Dashboard 重复了，对应的 breadcrumb 是正确的。

**Comment by iwisunny** [comment]
第二个有点不明确

**Comment by iwisunny** [comment]
breadcrumb 需要统一写到组件里

**Comment by imdonkey** [comment]
> 第二个有点不明确，感觉目前的不需要修改

写得不准确，"dev" 和 "admin" 界面右侧的 grid 间隔应该是 20px，现在是 24px.  “normal” 界面的 grid 间隔还是 24px 保持不变
