### ISSUE TITLE
实时编译添加 className 的问题

### ISSUE THREAD

**Issue by libangrui** [openpitrix/dashboard#4]
新增子组件时，实时编译添加的 className 加的不对。重新 run dev 一下就好了。先记录一下。

**Comment by iwisunny** [comment]
@libangrui add a label to issue, so we can filter it by category

**Comment by libangrui** [comment]
ok

**Comment by iwisunny** [comment]
Can not trigger webpack compiling when add new css class to component, but modify existed class is ok. Maybe caused by `webpack isomorphic tool`, see #20
