### ISSUE TITLE
权限控制问题

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#406]
dev登陆:
1:菜单列表没有做权限控制
2：公共仓库没有权限控制不正确

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/5114179/46126721-f2259b80-c260-11e8-83f7-d17b588a7a8e.png">

**Comment by whDongRui** [comment]
这个根据后端的调整已经查询两次repo了，现在能看到公共仓库。
菜单列表没有做权限控制在看到到菜单的bug中已经修复。
