### ISSUE TITLE
审核应用时的问题

### ISSUE THREAD

**Issue by zheng1** [openpitrix/dashboard#425]
![image](https://user-images.githubusercontent.com/4156721/46194399-e9ea6080-c333-11e8-9826-ed7cdfd462eb.png)

**Comment by zheng1** [comment]
![image](https://user-images.githubusercontent.com/4156721/46194513-4a799d80-c334-11e8-8366-0d848d1bda15.png)

**Comment by whDongRui** [comment]
先前是查app的数据来显示，现在这个已经修改，前端先查version的接口，再去查关联的app信息来显示数据的。已拒绝原因已经加上了。
<img width="950" alt="default" src="https://user-images.githubusercontent.com/38676269/46255586-61a1c200-c4d1-11e8-83ba-66582348a3d8.png">

<img width="721" alt="default" src="https://user-images.githubusercontent.com/38676269/46255589-6bc3c080-c4d1-11e8-9a4b-4ea4c5e45587.png">
