### ISSUE TITLE
【普通用户】界面细节及功能 Bug

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#428]
### 名词统一

- [x] “运行环境” 改为 “环境”
- [x] “仪表盘” 改为 “工作台”
- [x] “集群”改为“实例”
- [x] “云提供商” 改为 “云服务商”
- [x] “提供商” 改为 “云服务商”
- [x] “返回运行环境” 改为 “返回我的环境”
- [x] “活动”改为“操作日志”
- [x] “已购买”改为“已购应用”

### 翻译问题

- [x] 版本的发布时间、实例的创建时间等没有翻译，比如“Sep 08, 2018” “2 hours ago”之类的
- [x] 目前所有返回的提示内容都还是英文

### 未登录时

- [x] 查看应用详情的时候，“面包屑”需要换成“返回链接”，下面的内容距离顶部导航过远，需要往上调整为 70px
- [x] 点击“部署”之后要先跳转到登录界面，登录成功之后再进入部署表单。

### 登录页面

- [x] 登录界面的“记住我”无法选中

### 右上角

- [x] 下拉菜单增加图标，大小为 16px 设计稿参看 zpl://screen?sid=5b4867fc8ad0118c5fb6afb2&pid=5a422c2577a4a73371c92c01

### 工作台（Dashboard）

- [x] “欢迎来到OpenPitrix, 接下来你想做什么?..” 去掉最后的..
- [x] 对于第一次登录的用户，三个 card 都需要显示为 标题 + 介绍 + button, 对应的 button 链接依次：/store /runtimes /purchsed
- [x] 介绍的文字可以请周鹏飞再确认下，不要过多，内容要完整。
- [x] 当用户有了自己的环境之后，这三个 card 可以全部显示数据：人气最佳的应用，我的环境和最新实例，“更多...”的链接保持不变 依次：/store /runtimes /purchsed
- [x] “人气最佳的应用”中的应用链接达到的页面，目前出现了2个搜索框，需要去掉顶部的。
- [x] 中间的 Repo 换成 runtime ，样式不变，内容是 runtime provider 图标  + runtime 名称 + cluster 数量

### 商店-应用详情页面

- [x] 点击截图放大之后“前后箭头”点击无效
- [x] 部署的时候如果发现没有“环境”数据，表单中的“环境”一项需要提示“当前无可用环境，请前往创建”，点击创建链接到创建环境的表单。创建成功之后再返回回来。
- [x]  “Versions”没有翻译

### 已购应用

- [ ] 实例详情页面“CreateClusters” 之类的 job action 没有翻译
- [x] 实例详情页面“操作日志”的“更多->”需要与其他 card 的“更多...”做样式统一
- [x] 实例详情页面的“应用”链接要链接到商店的详情页面，而不是开发者视角的应用详情页面

### 我的环境

- [x] “All”需要翻译成“全部”
- [x] 没有描述的环境，也需要把描述的位置空出来，保证下面三个属性的位置始终在最底部
- [x] 我的环境第一列卡片左侧的阴影被挡住了
- [x] 创建环境的表单右侧“指导”改为“说明”
- [x] .Runtimes__addRuntime--13giW border-radius:2px hover 的时候改变背景颜色为 P10

### 账户设置

- [x] 修改密码不生效
- [x] 修改邮箱不生效
- [x] 修改用户名不生效

### SSH 密钥

- [x] bug: 新用户第一次登录时也能看到一些 ssh key 数据
- [x] 左侧的列表中间距离应该是 12px .Card__card--DAsUG
- [x] .SSHKeys__sshCard--3l-9Q .SSHKeys__title--1LjZc margin-bottom: 12px margin-top: 8px
- [x] .SSHKeys__sshCard--3l-9Q .SSHKeys__pubKey--1984n height: 32px line-height: 16px
- [x] 添加时的modal 标题 “Add SSH Key” 需要翻译成中文
- [x] .Modal__modal--1pI81 .Modal__body--1L_vm margin-bottom: 0px

**Comment by whDongRui** [comment]
详情见fix: Resolve github normal user bugs issue (https://github.com/openpitrix/dashboard/pull/493)

* 目前所有返回的提示内容都还是英文,这个会单独提issues来改，另外有些信息是后端接口返回的英文信息，这个得后端也要考虑国际化

* 实例详情页面“CreateClusters” 之类的 job action 没有翻译,这个是后端返回来的数据，如果不是固定的几种类型前端也翻译不全。
