### ISSUE TITLE
【开发者】界面问题及功能bug

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#434]
### 工作台 Dashboard

- [x] [第一次登录时] zpl://screen?sid=5b8f5da7264f8754b1784e7f&pid=5a422c2577a4a73371c92c01
- [ ] [私有仓库、自己的应用、自己的环境]三者只要其中一个有数据，就显示成 zpl://screen?sid=5b8f5da698c7586e1eef26cb&pid=5a422c2577a4a73371c92c01 且应用列表和实例列表都显示的是开发者自己的应用和测试实例。点击更多分别进入的是 “我的全部应用”界面和“测试实例”界面
- [x] “我的环境”部分链接的页面应该是 /runtimes 而不是 /dashboard/runtimes (应该是卡片视图)
- [ ] 文字内容也应该是描述“创建应用”和“测试实例”的，和普通用户的内容不一样。可以找鹏飞确认下。

### 创建应用

- [x] 第一步选择repo的时候经常遇到，只能选中一次，再点其他的 Repo 就选不上了，点击没反应
- [x] 第二步 “查看 <<Openpitrix开发指南>> 并了解如何制作配置文件” 需要改成书名号《》

### 我的应用

- [x] 左侧应用列表，选中之后需要有黄色的 border zpl://screen?sid=5b8f5da5264f8754b1784dbe&pid=5a422c2577a4a73371c92c01
- [x] .Menu__subNav--10VJY .Menu__apps--2Vb9- .Menu__app--2HeVh 图标的居中还差1px，好像去掉 line-height: 16px ，就可以了
- [x] 我的应用“全部列表”可以先不支持卡片视图，切换的 icon 也可以先去掉。
- [x] .Menu__subNav--10VJY .Menu__test--8tLAz .Menu__word--1mVsY left 改为 22px

### 我的应用详情

- [x] “Versions" 和 “Deploy” “Create Version”都需要翻译
- [x] “运行环境”改为“环境”
- [x] “集群”改为“实例”

### 账户设置&SSH密钥

- [ ] 当进入这两个功能界面时，左侧的二级导航不显示，主体内容靠左显示，设置一个最大宽度为 1128px
- [ ] 这两个页面都少了 breadcrumb
- [ ] 管理员身份登录时处理方式同上

### 应用仓库

- [x] .RepoList__repoList--1mOlm .RepoList__item--R2lLu margin-bottom: 12px

**Comment by iwisunny** [comment]
Will close this issue, not compat with v0.4 design styles
