### ISSUE TITLE
【终端用户-实例信息】

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#440]
- 公、私 IP没有区分颜色

- 样式有错位

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/5114179/46247732-30c67c00-c442-11e8-9183-f4bc7bc0b4d9.png">

**Comment by whDongRui** [comment]
这个和设计给的效果图应该是一样的，如下截图，这是helm的cluster详情，vm-based的cluster详情公有IP和私有IP是在一列显示，有颜色区分。
<img width="787" alt="default" src="https://user-images.githubusercontent.com/38676269/46583178-16655180-ca85-11e8-8c89-6b566f343297.png">
