### ISSUE TITLE
【开发者：查看商店】商店应用陈列内容有待商榷

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#441]
- 开发者点击商店页面，只能看到自己开发的应用，与普通用户看到的商店内容不一致

- 切换成普通用户后，看到的商店内容也与普通用户看到的商店内容不一致

- 开发者直接点击商店视图
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5114179/46247764-b813ef80-c442-11e8-95e9-78526e6c1e06.png">

- 开发者切换到普通用户的视图
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/5114179/46247772-c06c2a80-c442-11e8-8990-366618f56706.png">

- 普通用户商店视图
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/5114179/46247773-ce21b000-c442-11e8-8557-3730b0700c71.png">

**Comment by whDongRui** [comment]
这个目前是根据role的权限和用户来查询数据的，这个后端已经出来解决方案了，和没登录用户查询一致。


    为没有登录的用户返回管理员才能提供的内容应该怎么做: 服务器发送请求, 然后把返回的 access_token和secret_token放到内存里, 使用返回的access_token发请求, 流程和上面的登录类似

{
  "grant_type": "client_credentials",
  "client_id": "读取自配置文件",
  "client_secret": "读取自配置文件",
  "scope": ""
}

**Comment by whDongRui** [comment]
这个已经解决了，目前不同角色和未登录时看到的商店页面及其详情页面都是一样的数据和样式。解决详见PR(https://github.com/openpitrix/dashboard/pull/455)
