### ISSUE TITLE
【管理员：审核内容排序】

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#442]
- 开发者提交版本审核，没有置顶，在应用较多的情况下需要通过搜索框查询

- 同一应用不同版本的记录，最好能分组显示比较好归类

- 已提交，没有图标

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5114179/46247811-6455d600-c443-11e8-9603-ddfdfda857a6.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/5114179/46247815-66b83000-c443-11e8-87a0-fee28d4795df.png">

**Comment by whDongRui** [comment]
同一版本的version要一起显示出来得后端接口支持，目前是按创建时间在排序。现在只显示了三种状态，并加了过滤筛选。已提交的状态图标没有，是先前组件中缺少样式，现已经加上了。
<img width="991" alt="default" src="https://user-images.githubusercontent.com/38676269/46255487-1cc95b80-c4d0-11e8-89ce-b0edda962ad7.png">
