### ISSUE TITLE
【开发者：测试部署】

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#443]
- 开发者测试部署，选择版本的时候，有两个一样的版本号
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/5114179/46247827-8fd8c080-c443-11e8-8d2a-730059363dbb.png">

**Comment by whDongRui** [comment]
这个查询时没有过传status来过滤deleted的version,现在已经修改。
<img width="412" alt="default" src="https://user-images.githubusercontent.com/38676269/46255433-75e4bf80-c4cf-11e8-8e44-2c2dec70aa2c.png">
