### ISSUE TITLE
【终端用户：部署跳转页面比较孤立】

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#444]
- 终端用户在应用部署时候，跳转的实例页面比较孤立，需要优化
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/5114179/46247902-bba87600-c444-11e8-8eb4-b0b8a43dd92c.png">

**Comment by imdonkey** [comment]
这个不是应该跳转到已购应用页面么？默认左侧选中的是“所有应用”

**Comment by whDongRui** [comment]
部署成功后根据角色跳转不同的页面，这个昨天晚上已经修复。
