### ISSUE TITLE
登录页和上传应用，以及安装问题

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#469]
1.all-in-one安装的环境，登录页第一次访问会报： 访问令牌已过期。
![image](https://user-images.githubusercontent.com/40452856/46650413-fe014e00-cbce-11e8-96c6-1cbe6d5bc023.png)
1.1 k8s模式安装的环境，第一次登陆报：认证失败
![image](https://user-images.githubusercontent.com/40452856/46715694-c3adb480-cc93-11e8-844f-3130bb830d3c.png)

2.用sh脚本安装的环境，选择默认的两个 repo 上传应用包但是第一次上传都失败
![image](https://user-images.githubusercontent.com/40452856/46650457-2f7a1980-cbcf-11e8-8506-55e866ffff54.png)

3.用sh脚本安装的环境，部署VM应用失败
![image](https://user-images.githubusercontent.com/40452856/46650891-c1ceed00-cbd0-11e8-87f1-d186cf0ff1cf.png)

4. k8s模式安装时执行这条命令报错 
```
kubernetes/scripts/put-global-config.sh -i ${IP} -p {PORT}

Putting global config...
Error from server (AlreadyExists): pods "test" already exists
```

5. all-in-one 安装的OP，创建runtime验证超时
(环境：http://139.198.5.33:8000/)
![image](https://user-images.githubusercontent.com/40452856/46658229-cac9b980-cbe4-11e8-8002-54dfc895ef21.png)

**Comment by iwisunny** [comment]
第一个问题已修复，see: #476

**Comment by iwisunny** [comment]
问题3 也已经解决。 2和4 需要 @chilianyi 看下
