### ISSUE TITLE
应用备注信息不匹配

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#478]
备注对应的应用显示不正确,下图中商店显示haha的是vm应用，非helm应用
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/5114179/46778537-bef60880-cd46-11e8-94f6-3e103be9a4ad.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/5114179/46778543-c4ebe980-cd46-11e8-9d62-69131739bbc5.png">

**Comment by wangxhsoft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [英语转换BUG](https://trello.com/c/EvW3MpVk/11-%E8%8B%B1%E8%AF%AD%E8%BD%AC%E6%8D%A2bug)

**Comment by whDongRui** [comment]
这个已经改了，之前描述的值设置成defaultValue,导致总是取之前app中描述的值了。详见PR:fix: Add role desc, app version desc bug(https://github.com/openpitrix/dashboard/pull/488)
