### ISSUE TITLE
角色信息简介

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#479]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/5114179/46778587-f2389780-cd46-11e8-8fba-09233d3d46b8.png">

**Comment by iwisunny** [comment]
see: #436

**Comment by whDongRui** [comment]
这里面的文字已按给的文案换了，并且加了对应的英文翻译。

<img width="944" alt="default" src="https://user-images.githubusercontent.com/38676269/46846879-46f61400-ce14-11e8-854e-f1f6adf78776.png">
