### ISSUE TITLE
上架应用是否可以再发起上架审核？

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#480]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5114179/46778615-16947400-cd47-11e8-9203-95d538a7b020.png">

**Comment by whDongRui** [comment]
目前按后端接口中的逻辑，“已下架”应用只能管理员进行“恢复”操作变成“已上架”。
后端早期的有关于vesion操作的文档说明，下面是操作流程图，详见(https://github.com/openpitrix/openpitrix/issues/564#issuecomment-415313018)。备注：部分逻辑在后面开发测试中有所调整。

<img width="708" alt="default" src="https://user-images.githubusercontent.com/38676269/46847077-1bbff480-ce15-11e8-9c17-10764417a36f.png">

**Comment by iwisunny** [comment]
Is this issue still in discuss?
