### ISSUE TITLE
删除应用，左侧菜单无刷新

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#482]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/5114179/46778652-43488b80-cd47-11e8-80ad-2b0b309a27c0.png">

**Comment by whDongRui** [comment]
这个已经提pr修复了，详见： fix: Developer menu apps refresh bug (https://github.com/openpitrix/dashboard/pull/488)
