### ISSUE TITLE
修改文字

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#483]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5114179/46778692-6d01b280-cd47-11e8-9365-03bd3fd250d1.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5114179/46778709-81de4600-cd47-11e8-9e99-314cebb508ce.png">

**Comment by whDongRui** [comment]
deploy按钮翻译已加
<img width="939" alt="default" src="https://user-images.githubusercontent.com/38676269/46846793-d222da00-ce13-11e8-98a8-33b66a72b4c5.png">

”已购应用“已经换成了“已部署应用”，便英文暂时没改。
<img width="1191" alt="default" src="https://user-images.githubusercontent.com/38676269/46846832-03030f00-ce14-11e8-9e8f-287df6b41965.png">
