### ISSUE TITLE
【管理员】分类管理

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#484]
- [x] 1.分类管理没有看到 “创建” 按钮

- [x] 2. 点击右侧 “刷新” 按钮报错
![image](https://user-images.githubusercontent.com/40452856/46783823-456a1480-cd5e-11e8-9d75-11a1849f5b23.png)
![image](https://user-images.githubusercontent.com/40452856/46783841-66326a00-cd5e-11e8-8c28-cd328acc6c00.png)

- [ ] 3.不同浏览器数据显示不一致
![image](https://user-images.githubusercontent.com/40452856/46783866-7cd8c100-cd5e-11e8-87a8-25c843456b5d.png)

**Comment by whDongRui** [comment]
<img width="963" alt="default" src="https://user-images.githubusercontent.com/38676269/46846650-1d88b880-ce13-11e8-9bbb-0cdaa3c473b4.png">
上面中已经有创建按钮了，也能搜索过滤，刷新也修复了。详见PR(https://github.com/openpitrix/dashboard/pull/488)

safari没有数据，我本地的safari没有复现，后面有待进一步确认。

**Comment by iwisunny** [comment]
这个issue 可以关闭了？
