### ISSUE TITLE
create user

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#507]
- [ ] When create user, the default role of user to create should be the one admin chooses instead of normal one.

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-24 at 5 33 24 pm](https://user-images.githubusercontent.com/28859385/47421379-094d9f80-d7b3-11e8-8942-c5c6bdfb1237.png)

**Comment by whDongRui** [comment]
Resolve pr: https://github.com/openpitrix/dashboard/pull/514/files
Now remove the default role when create user.

<img width="776" alt="default" src="https://user-images.githubusercontent.com/38676269/47629085-1d5b1d80-db74-11e8-9f9a-48fb4584c314.png">
