### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#508]
- [x] I created two users, one developer and one normal user, but I still see only one user in the workplace.

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-24 at 5 38 57 pm](https://user-images.githubusercontent.com/28859385/47421694-bcb69400-d7b3-11e8-9124-7722a6e2d704.png)

**Comment by whDongRui** [comment]
Local or test environment did not reproduce this problem, can you provide accessibility URL?
