### ISSUE TITLE
unauthorized error

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#510]
- [x] It is better to jump to the login page automatically instead of popping up an unauthorized error

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-25 at 3 26 14 pm](https://user-images.githubusercontent.com/28859385/47483120-07dfae00-d86b-11e8-9f82-f13a9dd9f27d.png)

**Comment by iwisunny** [comment]
When api get unauthorized error, page will redirect to login.
