### ISSUE TITLE
validate repo

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#511]
- [ ] The validate flow is incorrect. It should throw error when click validate button. Now it show valid credential. But When I click ok button, it show error.
- [ ] The credential edit box should be longer.

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-25 at 3 42 49 pm](https://user-images.githubusercontent.com/28859385/47483844-cd771080-d86c-11e8-8b46-2f3424549e9c.png)

![screen shot 2018-10-25 at 3 42 57 pm](https://user-images.githubusercontent.com/28859385/47483861-d8ca3c00-d86c-11e8-9d5f-9ff0a5e3f22a.png)

**Comment by whDongRui** [comment]
Resolve PR: https://github.com/openpitrix/dashboard/pull/514/files
