### ISSUE TITLE
no runtime found

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#512]
- [ ] It is better to show error in red after the label runtime instead of popping up an error msg then disappeared.

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-25 at 4 15 43 pm](https://user-images.githubusercontent.com/28859385/47485792-745dab80-d871-11e8-991a-6f59c07616f5.png)

**Comment by whDongRui** [comment]
There will note "There is currently no available runtime, please go to create"  in page  when no runtime found .

Resolve PR: Deploy app query no runtimes add note (#497)

<img width="616" alt="default" src="https://user-images.githubusercontent.com/38676269/47633242-1c33eb80-db88-11e8-8715-604a15f2f091.png">
