### ISSUE TITLE
vxnet list to show when deploy an application

### ISSUE THREAD

**Issue by rayzhou2017** [openpitrix/dashboard#513]
- [x] The vxnet list is incomplete. You may need a paging, a search box, and show the name of vxnet aside of the vxnet id.

Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS 10.13.5

![screen shot 2018-10-25 at 4 37 40 pm](https://user-images.githubusercontent.com/28859385/47487162-7f660b00-d874-11e8-9cf0-18bfc3d87621.png)

**Comment by whDongRui** [comment]
Resolve pr: https://github.com/openpitrix/dashboard/pull/514/files
* The vxnet list is incomplete, becase query list default 10 datas, now add  parameter limit set max value. 
* The name of vxnet  not show,  becase the api return name is null.

<img width="276" alt="default" src="https://user-images.githubusercontent.com/38676269/47628976-8726f780-db73-11e8-90ea-28d7263f1532.png">

**Comment by iwisunny** [comment]
Currently vxnet list data is small, no need paging. If add paging, search box, we need discuss with our designer. The last problem is because name is empty.

This issue can be closed ?
