### ISSUE TITLE
V0.4 feature list

### ISSUE THREAD

**Issue by iwisunny** [openpitrix/dashboard#632]
## User
- Login
- App store
  - App search (By keywords or category)
  - App detail
  - Deploy instance
- Deployed apps
  - Deployed app detail
- My instances
  - Instance detail
- My runtimes
- Apply service provider (Same as ISV: Provider apply)
- Accout (base info, modify password, ssh keys)

## Developer
- My apps
- Create app / Add version
- App versions
 - Version detail
   - Version submit、cancel、 release、delete operation
   - Version check info (app edit、version edit、 app detail veiw)
- App information (base, redme, tos) 
- App audits
- User instances / Sandbox-instances
  - Instances detail

## ISV
- All apps
  - App detail (base info,  app statistics, user instance, online version, audit record)
- Review apps
  - Reveiw detail (app base, readme, tos, config files, update log, audit reviews)
  - isv, business_admin, develop_admin operations(review、pass、reject)
- Provider detail
  - Provider apply
- Team mebers
  - Roles

## Admin
- All apps (Same as ISV: All apps)
- Review apps(Same as ISV: Review apps)
- App categories
- Providers
  - Provider detail
- Applications 
  - Application detail (Pass or reject operation)
- Users

## New navigation
- User
- Developer
- ISV
- Admin

**Comment by whDongRui** [comment]
I'm doing Deployed apps and My instances.

**Comment by iwisunny** [comment]
@whDongRui 抽空把 developer, isv部分的功能列表补充上

**Comment by iwisunny** [comment]
This issue will be moved to wiki.
