### ISSUE TITLE
Login failed by all_in_one deployment

### ISSUE THREAD

**Issue by cxyfreedom** [openpitrix/dashboard#672]
## Description

Login with username and password failed

## Install Mode

All-in-One

## Snapshot

docker-compose ps
![image](https://user-images.githubusercontent.com/8132652/51155473-971cc080-18b2-11e9-9ec2-faade1784992.png)

error
![image](https://user-images.githubusercontent.com/8132652/51155504-ab60bd80-18b2-11e9-94ae-f16259feea1a.png)

**Comment by iwisunny** [comment]
@cxyfreedom Thank you for your feedback, I think this problem is due to our `iam` service is not ready. I will contact with our backend dev.

**Comment by cxyfreedom** [comment]
@chai2010 So if I want to avoid this problem, which version should I select or how to solve? Thanks.

**Comment by chai2010** [comment]
目前master分支的docker-compose已经包含了iam2服务，可以按以下命令测试：

1. git clone 最新的master
1. make compose-up
1. docker-compose ps

这时候应该可以看到iam2服务。

**Comment by cxyfreedom** [comment]
@chai2010 Solved. Thanks.
