### ISSUE TITLE
dev:我的应用，信息缺失

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#708]
点击我的应用，如果应用多的时候，缺失一些信息，**不知道有多少应用，一直在下拉滚动中加载**，信息需要添加，@吕婷
![image](https://user-images.githubusercontent.com/5114179/51581527-6583a500-1f03-11e9-89de-1c45e44c8296.png)

**Comment by iwisunny** [comment]
感觉没必要，app浏览页可以用滚动加载
