### ISSUE TITLE
user：测试环境的菜单

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#717]
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5114179/51613925-8a0d6a80-1f5f-11e9-93ae-39b6ed4192e7.png">

**Comment by whDongRui** [comment]
好的，非普通用户进入user的portal时不需要在菜单上显示“测试环境”的入口吧,刚已经修复了。修复[PR](https://github.com/openpitrix/dashboard/pull/721)


<img width="753" alt="default" src="https://user-images.githubusercontent.com/38676269/51651025-6715a180-1fc5-11e9-8343-7810f0132ba6.png">

<img width="1357" alt="default" src="https://user-images.githubusercontent.com/38676269/51651038-71d03680-1fc5-11e9-9448-1085eb6de30b.png">
