### ISSUE TITLE
商店：显示数量不对

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#720]
外面显示6个应用，点击app详情，就显示为7个
<img width="884" alt="image" src="https://user-images.githubusercontent.com/5114179/51614675-1f5d2e80-1f61-11e9-806c-adc987837298.png">

**Comment by whDongRui** [comment]
现在已经和首页的同步了，active_apps还能查出其它状态的app，现前端传了status参数。

<img width="1373" alt="default" src="https://user-images.githubusercontent.com/38676269/51651852-764a1e80-1fc8-11e9-9e35-fb3fa2a1187a.png">
