### ISSUE TITLE
ISV：vm测试实例：详情

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#727]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/5114179/51686965-695f1680-202c-11e9-80dc-a2b791803b63.png">
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/5114179/51686971-711ebb00-202c-11e9-9402-bf3a36e764e3.png">

**Comment by iwisunny** [comment]
路由跳转的问题，已修复

**Comment by iwisunny** [comment]
see #734
