### ISSUE TITLE
admin：business_admin无法拒绝审核

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#728]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/5114179/51688616-ed66cd80-202f-11e9-9033-b82ff62b38ea.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/5114179/51688807-53535500-2030-11e9-88c5-1dd868e75a30.png">

**Comment by whDongRui** [comment]
页面截图的显示已经修复了，详细见[PR](https://github.com/openpitrix/dashboard/pull/743)

<img width="1242" alt="default" src="https://user-images.githubusercontent.com/38676269/51738392-0b810c00-20ca-11e9-8f15-2ae326efdb93.png">
