### ISSUE TITLE
user 申请成为ISV，admin在应用商审核列表，直接就看到了这个用户下面有多个应用

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#735]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/5114179/51722518-99d89c00-2090-11e9-923c-676d467d9667.png">
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/5114179/51722553-b70d6a80-2090-11e9-97c7-8a1e326022bb.png">

**Comment by whDongRui** [comment]
@huojiao2006 ,帮忙看一下，统计是后端接口有问题有问题没改好。
<img width="1334" alt="default" src="https://user-images.githubusercontent.com/38676269/51722878-db1d7b80-2091-11e9-96b7-ab211192dcfd.png">
