### ISSUE TITLE
应用入驻审核，点击通过报错

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#736]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/5114179/51722599-defcce00-2090-11e9-8f0f-642d90c7d206.png">

**Comment by whDongRui** [comment]
这个是后来改统一路由造成的，之前代码约定的叫providerId，后来改成了applyId，但代码中的取值没有改造成的。现已经修复。

<img width="323" alt="default" src="https://user-images.githubusercontent.com/38676269/51723021-757dbf00-2092-11e9-85a4-fd1d14e4996a.png">

<img width="388" alt="default" src="https://user-images.githubusercontent.com/38676269/51722931-246dcb00-2092-11e9-98b1-f48746694220.png">
