### ISSUE TITLE
上传截图后没能正常显示

### ISSUE THREAD

**Issue by zheng1** [openpitrix/dashboard#738]
![image](https://user-images.githubusercontent.com/4156721/51724589-0788c600-2099-11e9-849c-8748bf16313c.png)

- [x] 打开时应该有截图, 但是没有显示出来
- [x] 刷新后提示有47/6张截图

**Comment by whDongRui** [comment]
这个之前是screenshots返回的数据结果是数组形式来解析的，现在已经改成基于字符串分隔符的解析了。
但同时上传多张截图时还有点问题，需要前后端联调一下。
