### ISSUE TITLE
user：申请成为isv

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#751]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/5114179/51891223-586e2680-23d9-11e9-854c-38a53065e585.png">
申请被拒绝后，收到拒绝邮件，二次申请，无法重新编辑信息

**Comment by whDongRui** [comment]
@huojiao2006 ,帮忙看一下这个问题。这个是拒绝后，再次提isv申请后端接口有逻辑上的限制。前端对审核中和通过了的申请，再次提交是会提示信息的。

<img width="804" alt="default" src="https://user-images.githubusercontent.com/38676269/51963943-06440880-24a0-11e9-9f16-60c67be865d1.png">

**Comment by huojiao2006** [comment]
it works now, please check again.

**Comment by whDongRui** [comment]
这个我用创建了一个普通用户验证已经好了，我把它关掉吧。
