### ISSUE TITLE
admin添加用户，用户收到邀请邮件

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#752]
![image](https://user-images.githubusercontent.com/5114179/51891604-93bd2500-23da-11e9-8d36-f3809d287b07.png)
邮件内容
1：但是在user端已经创建过了，所以在内容里面是不是把密码添加上；
2：把user的portal地址放到邮件内容里面；

**Comment by iwisunny** [comment]
可以让设计师先给设计稿

**Comment by wangxhsoft** [comment]
@imdonkey 邮件内容需要html样式，可以找stark要一下最终的邮件通知的内容。

**Comment by imdonkey** [comment]
@wangxhsoft @chilianyi 

此类系统邮件可以先使用这个模板 https://zpl.io/andAGxl

**Comment by chilianyi** [comment]
@imdonkey @wangxhsoft 全局设置里，需要加个首页url配置。 否则不知道地址。

**Comment by chilianyi** [comment]
@huojiao2006 改下这个问题吧。

**Comment by iwisunny** [comment]
@liiil825 给后端提供html模板就行
