### ISSUE TITLE
user升级成为isv,通过审核，但是界面上显示不匹配

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#753]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5114179/51892222-332ee780-23dc-11e9-9344-e1f59585b7fa.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/5114179/51892248-45a92100-23dc-11e9-819f-2a4a09f837f0.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/5114179/51892340-89038f80-23dc-11e9-87ad-cc466fec25e8.png">

**Comment by whDongRui** [comment]
这个应该是后端接口问题，真正通过审核后用户所属于的portal没有变过来（目前的角色），查用户信息时看的还是属于“普通用户”。ISV申请通过后应该属于isv。

**Comment by chilianyi** [comment]
same as https://github.com/openpitrix/dashboard/issues/751

**Comment by chilianyi** [comment]
fixed.
