### ISSUE TITLE
user:添加环境

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#755]
![image](https://user-images.githubusercontent.com/5114179/51892815-01b71b80-23de-11e9-84aa-cbad77bddc76.png)
连续添加2个环境就会出错

**Comment by chilianyi** [comment]
创建runtime credential 这块，只有第一次能够创建成功， 第二次创建其他的 credential，调用的api变成了用之前创建的runtime_credential 来创建runtime了。需要前端修复。

**Comment by iwisunny** [comment]
已修复，see #763
