### ISSUE TITLE
isv：样式问题

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#759]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/5114179/51919007-8d03d180-241d-11e9-9932-ca98f2d1a14f.png">

**Comment by whDongRui** [comment]
显示的样式问题已经修复，效果如下。

<img width="464" alt="default" src="https://user-images.githubusercontent.com/38676269/51965367-47d6b280-24a4-11e9-8445-9f49e3a835be.png">
