### ISSUE TITLE
isv：审核

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#761]
![25c6b204-7d98-4663-a7b1-220c56938ecb](https://user-images.githubusercontent.com/5114179/51920801-0c46d480-2421-11e9-9974-b302903cea75.png)

开发者，提交版本审核，又撤销审核，又重新提交，在审核列表里面不应该出现“撤销的审核事项”

**Comment by zheng1** [comment]
已修复, 如果还有问题就reopen
