### ISSUE TITLE
开发者：用户实例与沙盒实例页面指向的页面重复

### ISSUE THREAD

**Issue by FeynmanZhou** [openpitrix/dashboard#770]
## Describe the bug (简单描述问题)
 (A clear and concise description of what you expected to happen.)

开发者上传应用后，用户实例与沙盒实例页面指向的页面重复。

## Role using (使用角色)

开发者 （pf-dev@op.com）。

## To Reproduce(复现步骤)

开发者角色登录单机环境，上传一个应用后，在用户实例与沙盒实例页面指向的页面重复。

![image](https://user-images.githubusercontent.com/40452856/51972116-ae180100-24b5-11e9-82a7-5ec59263730b.png)

## Expected behavior(预期行为)

用户实例与沙盒实例页面应该是有所区分的，对于开发者来说应该只能看到沙箱实例才对吧。

**Comment by whDongRui** [comment]
这个开发者的沙盒实例应该是看到这个app在部署测试的数据(非user portal视图下操作的数据)
用户实例，是这个app上架之后真实用户部署的数据(user portal视图下操作的数据)

开发者也能到此到用户实例，他得关心他开发的app到底有多少用户去部署了。但在用户实例的页面应该只有查看的权限，没有操作的权限。面有沙盒实例的页面是即可以查看也可以操作。

这两个地方的操作权限我来控制一下，还有查询我也来改一下。

**Comment by whDongRui** [comment]
下面分别是用户实例和沙盒实例的截图，查询的接口已经有所区别了。便沙盒实例查询因后端接口权限的调整导致出错。别用户实例的列表页面和详情页面应该没有操作入口了。
解决代码请见[PR](https://github.com/openpitrix/dashboard/pull/771/files)

<img width="1319" alt="default" src="https://user-images.githubusercontent.com/38676269/51977104-76af5180-24c1-11e9-89f8-1256be0d45dc.png">

<img width="1319" alt="default" src="https://user-images.githubusercontent.com/38676269/51977124-89c22180-24c1-11e9-849f-b81ebe3dcb55.png">
