### ISSUE TITLE
admin：用户组织位置调整

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#778]
![image](https://user-images.githubusercontent.com/5114179/52033857-6babfe00-2561-11e9-9438-57e7f5e218c3.png)

对内放上面，对外放下面
对内：管理用户
对外：平台用户

**Comment by liiil825** [comment]
名称现在可以直接修改，顺序需要在group 里增加个字段用户设置用于排序  @chai2010

**Comment by wangxhsoft** [comment]
默认数据就修改过来

**Comment by liiil825** [comment]
好的
