### ISSUE TITLE
分辨率大的时候，不居中

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#783]
![image](https://user-images.githubusercontent.com/5114179/52044921-41b50480-257e-11e9-923c-bb5754d13471.png)

**Comment by whDongRui** [comment]
我的环境页面的样式已经优化了，目前效果如下截图。
代码参见[PR](https://github.com/openpitrix/dashboard/pull/784)

<img width="1382" alt="default" src="https://user-images.githubusercontent.com/38676269/52046595-13d1bf00-2582-11e9-9a86-1c43459e67fd.png">
<img width="1362" alt="default" src="https://user-images.githubusercontent.com/38676269/52046631-23e99e80-2582-11e9-98ad-629bf257d51c.png">
