### ISSUE TITLE
isv：应用审核，信息不匹配

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#785]
![image](https://user-images.githubusercontent.com/5114179/52099883-167af580-2610-11e9-9124-e214185cb6aa.png)

原因：开发者应该是提交了审核，产生了一条isv审核的记录，但是又取消了审核，二次提交，处理了最新的审核记录，但是第一次提交的审核记录还在，这个时候再点击进去就会产生信息不匹配的状态；
处理逻辑：如果开发者取消审核，这一条审核记录就处于作废的状态 可以在审核列表中显示一种作废的状态，这是一个流程上的漏洞，或者简单粗爆一些，直接不显示已取消的审核，个人觉得加一种状态会好一些，针对操作，有完整的记录链条；
@imdonkey @zheng1 @whDongRui

**Comment by whDongRui** [comment]
这个页面的数据我用isv的用户登录进出看了一下，可以看到两个不同的review_id对应了相同的app_id和version_id,而通过version_id查到的的状态为active已通过。

应该是提交审核后进行了撤销操作后又提交就造成又有了新的审核数据，新的审核数据审核通过了。但之前撤销之前的那条待审核数据的状态没有变成“已撤销”，造成了在待审核审核中多了一条数据。

按照上面Alex说的在开发都进行撤销操作时，应该对对应待审核的数据要做一下状态的改变，不然撤销后还有待审核的数据。

@zheng1 @chilianyi @wangxhsoft 

![image](https://user-images.githubusercontent.com/38676269/52692736-aff6bf80-2f9f-11e9-9579-561b9d42e6a1.png)

![image](https://user-images.githubusercontent.com/38676269/52692778-d3216f00-2f9f-11e9-875e-c7bdc9d3f5df.png)

![image](https://user-images.githubusercontent.com/38676269/52692213-43c78c00-2f9e-11e9-8c14-187dcf260495.png)

**Comment by whDongRui** [comment]
这个问题目前应该不存了，审核中的version目前一般情况下没有入口可以撤消了(除非提交审核后，再开另外一个窗口去登录审核)。

另外，上午测试的结果是审核中的version撤消后不会再出来在待审核列表中了。
