### ISSUE TITLE
修改环境变量展示问题

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#788]
![screenshot from 2019-02-02 15-25-41](https://user-images.githubusercontent.com/5917832/52161524-0989ff00-2701-11e9-8dc9-cc6cf6140a25.png)

**Comment by iwisunny** [comment]
@chilianyi 这个具体要展示成什么样?，目前是按yaml展示

**Comment by iwisunny** [comment]
vmbased 集群按json展示，其它展示为yml
