### ISSUE TITLE
修改角色权限页面，现在没有自动展开

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#789]
![screenshot from 2019-02-11 11-22-53](https://user-images.githubusercontent.com/5917832/52545037-754e2500-2def-11e9-9b8d-a65671c28fac.png)

需要点击一下“全部”，才会展开
![screenshot from 2019-02-11 11-24-19](https://user-images.githubusercontent.com/5917832/52545058-97e03e00-2def-11e9-9c5f-5a6f5cb76e4b.png)

目前无法修改。

**Comment by iwisunny** [comment]
自动展开的问题已修复，无法修改的问题让 @liiil825 看下
