### ISSUE TITLE
User 界面功能及部分设计还原问题（part-1）

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#790]
- [x] 1. 未登录时，左上解显示 logo 加平台名称，不显示四个功能菜单 [https://zpl.io/V4QjOXN](https://zpl.io/V4QjOXN)
    1. 登录链接的颜色是黄色 Y100
    2. logo 图标可在 [https://zpl.io/V4QjOXN](https://zpl.io/V4QjOXN) 上下载
- [x] 2. 登录成功之后，“应用商店”“已部署应用”等导航的文字有 font-weight: 500 的样式。
- [x] 3. 登录成功之后，用户名与箭头的间距是 4px, 且箭头图标大小是 12px * 12px。
- [x] 4. 登录成功之后，用户名的下拉菜单宽度是 180px，且 item 之间的间距不对，具体参看 [https://zpl.io/boZxQqG](https://zpl.io/boZxQqG)，下拉菜单距离页面顶部是 44px，头像右侧的用户名字号是 14px。
- [x] 5. 普通用户界面的下拉菜单中，没有“运行环境”这一项，且目前“修改密码”和“SSH 密钥”的页面链接是错误的。
- [x] 6. “帐户信息”与“修改密码”的样式请参看 [https://zpl.io/bPXrnJy](https://zpl.io/bPXrnJy) [https://zpl.io/2yz1Qpo](https://zpl.io/2yz1Qpo) Tab 菜单的样式与设计稿不一致，内容改为页面内居中。
- [x] 7. 登录成功之后，“应用商店” 页面显示为搜索框在右侧的 header [https://zpl.io/V0RAWol](https://zpl.io/V0RAWol)
    1. 2种高度的 header , 以及中间文字的样式，间距与设计稿不一致，请仔细核对
- [x] 8. 应用 Card 的 hover 效果与示例还是有出入 [https://codepen.io/imdonkey/pen/omXdoJ](https://codepen.io/imdonkey/pen/omXdoJ)
    1. 应用名称的字体以及字重
    2. 应用图标是有3px的圆角的
    3. hover 之后 “应用服务商”“交付类型”是从下方居左的位置上移，不是居中 
    4. 右侧整体内容距离 header 是 32px, 与左侧的目录水平对齐

        [](https://www.notion.so/8f2a872731cb4c1eb52bb865364d3077#fa865af5e2ac416ba0f09bab7e335878)

- [x] 9. 左侧目录 icon 以及文字的 hover 效果参看设计稿 [https://zpl.io/V0RAWol](https://zpl.io/V0RAWol)
- [x] 10. 整个应用中心页面的栅格请参看 zeplin 上的布局模板 [https://zpl.io/VKoqRjX](https://zpl.io/VKoqRjX)
- [x] 11. 页面的 title 显示规则：平台名称 + 模块名称，比如“QingCloud 应用中心 - 应用商店”
- [x] 12. Footer 的 logo 没有垂直居中，且整体高度是 72px
- [x] 13. 一旦搜索框从左侧移到了右侧就不要再变回来了，所有搜索行为都在右侧完成，目前在右侧清除掉关键字之后就还原到左侧，不符合预期。
- [x] 14. 搜索结果页面刷新之后，搜索框也要一直在右侧，不能跑来跑去
- [x] 15. 应用详情页面
    1. 没有“应用服务商编号信息”
    2. 截图的分页样式不是圆角，高度和间距都不对，请参看设计稿
- [x] 16. 部署应用页面
    1. 环境的下拉菜单需要加下云平台的图标
    2. 交付类型和版本号的 button group 样式不对
    3. Helm 类应用的配置文件样式与设计稿不一致 [https://zpl.io/VxRnKn3](https://zpl.io/VxRnKn3)
    4. 没有环境时的提示内容不对，这里不是测试环境，请去掉“测试”相关的内容，与开发者的部署测试实例界面要区分开。包括创建“我的环境”时的界面，不应该出现“测试”二字。
- [x] 17. 我的环境
    1. “暂不支持”的 tooltip 样式与设计稿不一致
    2. 我的环境增加了 frontgate 的信息展示，具体设计稿参看 [https://zpl.io/aNKROve](https://zpl.io/aNKROve) [https://zpl.io/V4Q3Rn8](https://zpl.io/V4Q3Rn8) （整个环境 card 点击进入详情页面）
- [x] 18. 创建环境
    1. 选择已有的授权信息样式与设计稿不符：[https://zpl.io/agrRzXM](https://zpl.io/agrRzXM) 且 hover 时不要出现元素跳动的情况。
    2. 不同的云平台提示的文字内容，以及输入框的内容都要有区别，比如 aliyun 的 api 地址目前就写成 qingcloud 的了..，另外下面如何获得这些信息的内容出不对。
- [x] 19. "SSH 密钥"部分如果有时间请按设计稿更新一下 [https://app.zeplin.io/project/5bcd7933e2c97b18e1a53d47/dashboard?seid=5c3865e5fbb8efbdff5bb4a9](https://app.zeplin.io/project/5bcd7933e2c97b18e1a53d47/dashboard?seid=5c3865e5fbb8efbdff5bb4a9)

**Comment by whDongRui** [comment]
修改说明：
问题16 iii.Helm 类应用的配置文件样式与设计稿不一致 https://zpl.io/VxRnKn3
Helm类的应用部署只需要修改values.yaml配置的值和增加一个部署实例名称，不需要设计稿中的节点设置和服务依赖的配置。所以这个总量暂时没做修改。

问题19 
* 之前的接口是SSH key 和 cluster node的绑定，这次调整样式时右侧列表还是显示的查询是nodes，不是clusters
* 还有目前后端接口暂时不支持SSH key编辑功能，这个暂时没有加上去
* 另外，ssh key的创建只支持“使用已有公钥”的模式，下载模式不支持
