### ISSUE TITLE
开发者创建app成功后，用返回的app_id查询不到app详情

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#793]
开发者上传压缩包创建app成功后，用返回的app_id查询不到app。并且在全部应用中也查询不到新创建的app数据。

之前这一块都是好的没什么问题，这个问题可能和正在改的IAM有关。

![image](https://user-images.githubusercontent.com/38676269/52694204-df0f3000-2fa3-11e9-958a-ca4c3d1adc03.png)

![image](https://user-images.githubusercontent.com/38676269/52694239-f9e1a480-2fa3-11e9-9785-7c201d478c2a.png)

![image](https://user-images.githubusercontent.com/38676269/52694297-24cbf880-2fa4-11e9-9cdb-f817f87fef9b.png)

**Comment by chilianyi** [comment]
开发者创建的app应该是debug的吧， 应该用debug app 那个接口查询。

**Comment by whDongRui** [comment]
创建app应该不用分debug吧,  只能开发者(或者isv在开发者的视图)才能创建，查询需要区分。刚看了swagger-ui，好像也就一个创建app的接口。

<img width="759" alt="default" src="https://user-images.githubusercontent.com/38676269/52695239-ebe15300-2fa6-11e9-8ac7-e4215ac2bd00.png">
