### ISSUE TITLE
分类接口查询的结果不一致

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#802]
1. 用管理登录的话，首页和里面的页面查询分类返回的数据不一致。
![image](https://user-images.githubusercontent.com/38676269/52932545-0773a180-338b-11e9-9b3c-65124593bbd2.png)
![image](https://user-images.githubusercontent.com/38676269/52932554-0e021900-338b-11e9-8bd6-f2dabb61b375.png)

2. isv,普通开发者登录后查询不到分类数据，但页面设计上有分类下拉选择框，需要查询分类数据。

**Comment by iwisunny** [comment]
接口查询限制的，see: #818
