### ISSUE TITLE
“全部服务商”或“入驻申请”列表查询不到数据

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#807]
用普通用户登录提交ISV申请，再切换admin账号登录，在“全部服务商”或“入驻申请”列表中看到新提交的数据，并且这两个列表的数据一直都是空的。

<img width="1289" alt="default" src="https://user-images.githubusercontent.com/38676269/52995962-158ef400-3457-11e9-853b-659459b44c6f.png">
<img width="1310" alt="default" src="https://user-images.githubusercontent.com/38676269/52995987-2475a680-3457-11e9-9841-bd487fb53ab9.png">

**Comment by chilianyi** [comment]
这个问题应该修复了，请确认下。

**Comment by whDongRui** [comment]
好的，现在能查到了。
