### ISSUE TITLE
云环境设置(服务商的开关)集成

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#815]
1.平台设置-云环境中服务商开关的开启和关闭，当点“关闭”需要验证该服务商下是否有runtime.

2.我的环境中服务商获取应该有后台接口来判断哪些服务商是开启的，那些服务商是关闭的

**Comment by iwisunny** [comment]
@huojiao2006 这里的接口要提供下

**Comment by iwisunny** [comment]
已完成，see: #819
