### ISSUE TITLE
SSH key 和节点的绑定总是失败

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#816]
调整SSH页面样式时测试SSH key 和节点的绑定，结果绑定总是失败。Cluster的操作日志提示的也是AttachKeyPairs操作失败。

![image](https://user-images.githubusercontent.com/38676269/53149123-c6c49400-35e7-11e9-9f9a-4c5cf93a6c05.png)

**Comment by chilianyi** [comment]
已知问题，后面会修复。
