### ISSUE TITLE
User 界面功能及部分设计还原问题（part-2）

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#828]
# 普遍问题

- [ ]  所有出现 OpenPitrix 字眼的地方都应该替换成用户设置的平台名称（产品技术支持信息除外，目前界面上也没有显示这部分，需要设计提供）
- [x]  左上角的 logo 需要可点击，点击之后返回应用商店主页
- [x]  未登录时的 左上角的平台名称样式： .Header__header--1UDpl .Header__logoName--sbfUx margin: 14px 8px
- [x]  所有加载的 icon 都要统一改为：[https://zpl.io/agrBDX9](https://zpl.io/agrBDX9) 这样的，大小为 36px * 36px
- [x]  .pi-table 中的 overflow-x: auto 能否去掉，不然也是有卡片阴影被挡住的问题
- [x]  登录的时候虽然能登录成功，但还是能看到点击完登录 button 之后，在表单上方有一个错误提示闪过
- [x]  关于顶部出现的操作提示，请更新下样式：[https://zpl.io/VxR59Rg](https://zpl.io/VxR59Rg) 且有动效，动效请参看 [http://192.168.5.217/components/message](http://192.168.5.217/components/message)
- [ ]  所有删除的确认 Modal 中需要显示选中的内容信息，并且右下角的确认 button 文字是“删除”，类似 [https://zpl.io/2ZjKRBJ](https://zpl.io/2ZjKRBJ)

# 个人中心

- [x]  用户名需要支持修改
- [x]  下拉菜单第一个选项不对：参看：[https://zpl.io/2plgdBr](https://zpl.io/2plgdBr)
    - [x]  不管同身份对应的选项是不同的Admin - “管理后台” ISV - “服务商中心”
    - [x]  相对的在后台的个人中心下拉菜单中显示的都是 “应用中心”
- [x]  下拉菜单中少一个 “SSH 密钥”的入口
- [x]  帐户信息、修改密码、SSH 密钥这些应该有对应的 URL，保持刷新页面之后先选内容不变，不然下拉菜单中的入口就没有意义了，像有 bug

# SSH 密钥

- [x]  左侧的 “。。。” 的各种状态请参看 [https://zpl.io/29PEdQl](https://zpl.io/29PEdQl) [https://zpl.io/aXkJOKE](https://zpl.io/aXkJOKE) 是小号的 more button , 且下拉菜单与 button 是右对齐，上边的距离是 4px
- [ ]  

# 应用商店

- [x]  搜索框：.Banner__banner--2JeXO .Banner__description--qDJNR overflow: hidden 去掉，不然搜索框会距离上面的文字多2个px
- [x]  搜索框的 placehoder 字体大小是 14px
- [x]  "暂无应用数据!" 对应的样式调整：AppList__noData--2qTV6 line-height: 20px
- [x]  右侧的应用列表父容器 .AppList__appList--32zLL overflow: hidden 能否去掉，不然第一列的卡片阴影会被挡住

# 我的环境

- [ ]  左侧如果是选中的云平台，其 logo 应该是彩色的，这个需要设计这边如何输出？这个 logo 也和其他 icon 一样，但是不知道如何显示彩色主题。
- [x]  那些没有支持的云平台图标与名称都需要左对齐，另外，图标和文字需要垂直居中，目前差几像素，但我没找到具体原因。
- [x]  环境卡片右上角的更多操作按钮样式也有问题，请参看 [https://zpl.io/and6xNY](https://zpl.io/and6xNY) （与 SSH 密钥的第一问题一样，我尝试改过，但好像多处使用，影响比较多）
- [x]  "授权信息"的空页面还需要调整为与“我的环境”的页面一致 [https://zpl.io/2EPY4vx](https://zpl.io/2EPY4vx)
- [x]  “我的环境”列表页面的 card 有hover 效果，请参看 [https://zpl.io/and6xNY](https://zpl.io/and6xNY)
- [x]  “切换授权信息”的表单请参看 [https://zpl.io/2vKGDKr](https://zpl.io/2vKGDKr) （当前的样式不同，且不可选）

# 添加环境

- [x]  页面小标题应该是：添加环境 1/2 (只有在开发中心和管理后台才是“测试环境”)
- [x]  页面标题能否加下云平台名称：比如：提供 QingCloud 环境授权信息
- [x]  右上角与左上角的 返回 退出 button 都是有 hover  active 等状态的，请参看 [https://zpl.io/29PEdQl](https://zpl.io/29PEdQl)，而且“返回” button 跑到右边去了，应该是在左上角。且← 不是字符，是图标。
- [x]  在有"授权信息"的情况下，选择与创建之间的分隔线需要一直存在。
- [x]  关于“如何获取授权信息”的提示，文字中需要可以支持链接，在新窗口打开。（具体内容我晚点提供）
- [x]  "信息验证中"的样式有问题，会跳到 “验证 ” button 后面，请参看 [https://zpl.io/2ylKOXq](https://zpl.io/2ylKOXq)
- [x]  "继续" button 的 icon 在文字后面
- [x]  选择“区域”的下拉菜单，默认显示“请选择”而不是完全空。

# 已部署的应用

- [x]  空数据状态下没有占位图标，请使用 app 图标

# 我的实例

- [x]  没有过滤掉 frontgate 数据

**Comment by imdonkey** [comment]
@liiil825 关于创建环境时如何获得各平台的授权信息，我上传到 zeplin 上了 https://zpl.io/aRE61Bp

comments 里有对应的 url 地址。

**Comment by iwisunny** [comment]
@liiil825 这个issue 可以关了？

**Comment by liiil825** [comment]
嗯，可以先关了，还有几个可以单独再提
