### ISSUE TITLE
添加商务审核用户，登陆进来预期不对

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#840]
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/5114179/53783739-cadca400-3f4d-11e9-8e27-5034f9c00e5c.png">

**Comment by wangxhsoft** [comment]
个问题应该是用新创建的角色去创建的用户，再去登录就查询不到用户详情。我刚创建了一个角色，再用它创建新用户去登录就有问题。

**Comment by chilianyi** [comment]
已修复，请再次确认。

**Comment by whDongRui** [comment]
和上一个issue是一样的总是，这个前端今天按最新接口内容把这块的逻辑稍微重构了。详细代码PR:https://github.com/openpitrix/dashboard/pull/864(#864)
