### ISSUE TITLE
新创建一个角色，再用这个角色来创建的用户登录时后端接口查userDetail报错

### ISSUE THREAD

**Issue by whDongRui** [openpitrix/dashboard#842]
用户名test@op.com/zhu88jie
test@op.com关联的角色是新创建的test角色

<img width="518" alt="default" src="https://user-images.githubusercontent.com/38676269/53784450-493a4580-3f50-11e9-8958-48d5b9534ec9.png">

**Comment by chilianyi** [comment]
这个问题昨晚修复了，创建个新的用户试试。

**Comment by whDongRui** [comment]
@chilianyi 这个前端今天按最新接口内容把这块的逻辑稍微重构了。详细代码PR:https://github.com/openpitrix/dashboard/pull/864(#864)
