### ISSUE TITLE
全局样式问题

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#843]
- [ ]  button group 样式：比如”未处理“”已处理“ 部署应用时的”版本号“以及交付方式的选择。参看 [https://zpl.io/b6jJ3rj](https://zpl.io/b6jJ3rj)
- [ ]  tab 和 tab 下的内容应该是一个整体，目前只有 tab 下的内容有阴影， tab 没有，感觉比较割裂 具体样式参看 [https://zpl.io/ando77Q](https://zpl.io/ando77Q) ，有这个问题的页面很多，请仔细检查。

**Comment by whDongRui** [comment]
Solve see PR:fix: Button group and table no data styles(#850)
