### ISSUE TITLE
应用版本详情的配置文件加载不出来

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#856]
- [x]  第一次进入版本详情页面时没有”配置文件“的内容，切换 tab 之后才有，刷新页面之后又不显示了。
<img width="1280" alt="2019-03-06 12 14 54" src="https://user-images.githubusercontent.com/316145/53855646-7d257180-4009-11e9-8c76-f9954700454a.png">

**Comment by iwisunny** [comment]
see: #864
