### ISSUE TITLE
关于创建应用、添加交付方式以添加新版本的页面标题

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#857]
这三类页面的子标题与主标题应该是不一样的

### 创建新应用
第一步
子标题：创建新应用 1/3
主标题：选择应用的交付方式

第二步
子标题：创建新应用 2/3
主标题：上传 VM 规范的应用配置文件 (把前一步选择的交付方式信息带上)

第三步
子标题：创建新应用 3/3
主标题：确认应用基本信息

### 添加新版本
第一步
子标题：为 Wordpress 添加版本 (把应用名称带上)
主标题：上传 VM 规范的应用配置文件

### 添加新交付方式
第一步
子标题：为 Wordpress 添加交付方式 1/3 （把应用名称带上）
主标题：选择要添加的交付方式

第二步
子标题：为 Wordpress 添加交付方式 2/3
主标题：上传 VM 规范的应用配置文件 (把前一步选择的交付方式信息带上)

第三步
子标题：为 Wordpress 添加交付方式 3/3
主标题：确认应用基本信息

<img width="1019" alt="2019-03-06 1 33 37" src="https://user-images.githubusercontent.com/316145/53858272-7a7c4980-4014-11e9-8f0b-1edb1498f422.png">

**Comment by imdonkey** [comment]
添加新版本
第一步
子标题：为 Wordpress 添加版本 (把应用名称带上)
主标题：上传 **VM** 规范的应用配置文件

以上这种情况的主标题还是没有带上 ”交付方式“的信息

**Comment by liiil825** [comment]
嗯，加上了
