### ISSUE TITLE
User-实例详情

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#882]
![image](https://user-images.githubusercontent.com/5114179/54328268-3e666b80-4648-11e9-8773-be47703df31a.png)

**Comment by imdonkey** [comment]
- 我看了页面样式，确实还是有空间的，
- 另外右侧的 Table 不要出现阴影了，外面边框有阴影就可以了。
- 左下角的操作日志可以翻译成中文么？

**Comment by whDongRui** [comment]
右侧卡片的信息现在都有了，代码详情[PR](#957)
* 应用和版本都显示了，环境名称也能显示全了
* 操作日志已经翻译成中文了
* 右侧table没有阴影了

<img width="1327" alt="图片" src="https://user-images.githubusercontent.com/38676269/54742810-58322080-4bfd-11e9-83c2-5ed664acfbb3.png">
