### ISSUE TITLE
ISV：双返回icon

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#885]
![image](https://user-images.githubusercontent.com/5114179/54328421-cf3d4700-4648-11e9-9ab5-e26ceb9c5ec3.png)

**Comment by imdonkey** [comment]
<img width="876" alt="屏幕快照 2019-03-14 上午11 27 20" src="https://user-images.githubusercontent.com/316145/54329320-2a246d80-464c-11e9-987e-e052bea5145f.png">

请前端同学做以下调整：
当 ISV 进入应用开发模块之后，左上角默认显示“dev icon + 应用开发”，鼠标 hover 时变成“return icon + 返回服务商中心”

下个版本再针对导航这块做进一步优化。

**Comment by whDongRui** [comment]
导航样式已经调整，效果如截图所示。修复代码请参见[PR](#968)

<img width="991" alt="图片" src="https://user-images.githubusercontent.com/38676269/54748636-288b1480-4c0d-11e9-897a-56f7a41356e9.png">

<img width="1027" alt="图片" src="https://user-images.githubusercontent.com/38676269/54748642-304ab900-4c0d-11e9-9821-3d8302ccccb8.png">
