### ISSUE TITLE
user：我的环境

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#886]
![image](https://user-images.githubusercontent.com/5114179/54328466-f72caa80-4648-11e9-9b59-e830cce99dc8.png)
显示问题，不精致

**Comment by imdonkey** [comment]
这个按设计规范调整下 https://zpl.io/29PEdQl
参看其中 小号 more button 的样式
<img width="101" alt="屏幕快照 2019-03-14 上午11 20 58" src="https://user-images.githubusercontent.com/316145/54329087-4247bd00-464b-11e9-87a2-6a8e7cd93e33.png">
