### ISSUE TITLE
button group 样式

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#891]
<img width="241" alt="屏幕快照 2019-03-14 上午11 35 52" src="https://user-images.githubusercontent.com/316145/54329628-62787b80-464d-11e9-9a93-bbc2a53e242d.png">

## 应用详情

- [x] 显示交付方式和版本号的地方样式与设计稿不一致，不应该有两层 border 出现，https://zpl.io/VxRnnwJ 且button 外围是有阴影效果的。

## 应用部署

- [x] 如果版本号过长，或过多，需要按以下方式做处理：
<img width="417" alt="屏幕快照 2019-03-14 上午11 41 21" src="https://user-images.githubusercontent.com/316145/54329780-2c87c700-464e-11e9-9cf5-2010013ecfe2.png">
类似官网计算器上相关组件的处理方式（换行处理，保持起始有圆角）：

https://www.qingcloud.com/pricing#/InstancesKVM

<img width="773" alt="屏幕快照 2019-03-14 上午11 42 20" src="https://user-images.githubusercontent.com/316145/54329808-49bc9580-464e-11e9-8afc-310fdb15af16.png">

**Comment by whDongRui** [comment]
版本号是由用户输入的，有的比较长有的比较短，这样有的一行可能显示3个，有的一行只能显示2个，甚至有的只能显示下1个。这个要控制那个border的样式不太好调整。

**Comment by imdonkey** [comment]
每个选项的宽度是根据内容长短来定的，保持左右 padding 不变就可以，一行显示不下就换行，没问题。

**Comment by iwisunny** [comment]
![image](https://user-images.githubusercontent.com/4971916/54699243-a26ac180-4b6b-11e9-8397-6e48210e83c2.png)

类似这样展示了
