### ISSUE TITLE
ISV：全部应用列表各信息显示问题

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#892]
<img width="180" alt="屏幕快照 2019-03-14 上午11 49 38" src="https://user-images.githubusercontent.com/316145/54330198-be440400-464f-11e9-90a8-c2b4b3cc7de5.png">

### 交付方式

- [x] 与开发应用时选择的文案不统一：vmbased -> VM helm -> Helm

### 开发者
- [x] 需要显示出开发者的用户名以及邮箱，只显示 ID 没有可读性。

### 分类 和 部署次数
- [x] 以上两个信息都没有显示出来

**Comment by whDongRui** [comment]
* 交付方法已经将value转化成name显示了

* 部署次数的查询也加上去了(应该是统计普通用户的部署数据，测试环境上的部署不统计吧)

<img width="1120" alt="图片" src="https://user-images.githubusercontent.com/38676269/54332301-8bead480-4658-11e9-8085-9d8ff43bff8e.png">

**Comment by iwisunny** [comment]
这个都check了，可以关闭了？

**Comment by whDongRui** [comment]
admin 登录显示 应用服务商，isv登录显示开发者，这个昨天晚上给修复了，代码见[PR](#921)

<img width="1122" alt="图片" src="https://user-images.githubusercontent.com/38676269/54411517-adb48c00-472a-11e9-9aa0-09d5cbf46335.png">
