### ISSUE TITLE
应用审核界面样式

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#893]
<img width="426" alt="屏幕快照 2019-03-14 下午12 39 15" src="https://user-images.githubusercontent.com/316145/54331735-4af1c080-4656-11e9-801d-f8b1b911262f.png">

以上审核步骤之间的间距需要缩小且中间有连线，参看设计稿 https://zpl.io/VkwDDgW

**Comment by whDongRui** [comment]
好的，这个我一会调整一下。

**Comment by whDongRui** [comment]
调整后的样式如下截图：
<img width="473" alt="图片" src="https://user-images.githubusercontent.com/38676269/54332944-5e535a80-465b-11e9-8ca9-9bf76c022652.png">

**Comment by whDongRui** [comment]
修复代码请参见[PR](#912)
