### ISSUE TITLE
名称的正则表达式名称验证，调整为表单验证，用中文提示

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#895]
![image](https://user-images.githubusercontent.com/5114179/54332738-99a15980-465a-11e9-9060-cb219e463a3b.png)

**Comment by imdonkey** [comment]
输入框下面加一句格式的提示吧。 @liiil825 比如：

只包含小写字母和数字。

**Comment by liiil825** [comment]
好的
