### ISSUE TITLE
部署应用界面样式

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#900]
![image](https://user-images.githubusercontent.com/316145/54333094-16810300-465c-11e9-9e2b-95338fbe29a0.png)

所有显示参数配置文件的地方都与设计稿样式不一致，请参看 https://zpl.io/and66eO

**Comment by whDongRui** [comment]
这个helm类的部署没必要改成和设计一样的，返回数据中没有节点设置，服务，环境之类的内容。
