### ISSUE TITLE
开发中心左侧导航 icon 对齐问题

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#901]
.SideNav__topNav--1wFRV>.SideNav__navItem--2AjD0 .SideNav__iconLink--3yPBp>span {
    position: relative;
    top: 3px;
    left: -3px;
}

以上top left 定义去掉就可以让没有图片的 icon 水平和垂直对齐，但是如果是有图片的 icon 还是会偏下一些。

**Comment by iwisunny** [comment]
就是为了处理有img的情形的

**Comment by whDongRui** [comment]
目前导航的样式调整如下截图，应该都对齐了。修复代码请参见[PR](#968)。

不过开发者登录的导航的图标调整的和其它角色的导航图标一样大小了，为20px(先前好像是24px，这个需要调大一点吗？)。

<img width="1343" alt="图片" src="https://user-images.githubusercontent.com/38676269/54748853-d1d20a80-4c0d-11e9-8c48-ac5ab767770a.png">
