### ISSUE TITLE
ISV：应用详情页面的链接地址无效

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#902]
<img width="1316" alt="屏幕快照 2019-03-14 下午1 26 27" src="https://user-images.githubusercontent.com/316145/54333275-d3735f80-465c-11e9-8f19-7d7ec9c5d223.png">

”去商店中查看“点击没有到达对应的应用详情页面

**Comment by whDongRui** [comment]
已经修复了，之前全部app是把所有的都查出来了，包括没上架的，当时就把这个地方的链接做成了home,现在已经改成对应的详情页面了。

<img width="673" alt="图片" src="https://user-images.githubusercontent.com/38676269/54412221-e48ba180-472c-11e9-9561-9928a0e0679d.png">
