### ISSUE TITLE
admin:应用管理&审核

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#903]
![image](https://user-images.githubusercontent.com/5114179/54333304-f00f9780-465c-11e9-98cd-2957b8454d41.png)
![image](https://user-images.githubusercontent.com/5114179/54333497-a07d9b80-465d-11e9-82eb-19b532347a27.png)
![image](https://user-images.githubusercontent.com/5114179/54333555-e175b000-465d-11e9-99df-3df34e9cfe5e.png)
![image](https://user-images.githubusercontent.com/5114179/54333616-27cb0f00-465e-11e9-945f-134a158be172.png)

![image](https://user-images.githubusercontent.com/5114179/54333864-028ad080-465f-11e9-9a65-1f4daeaa4958.png)
![image](https://user-images.githubusercontent.com/5114179/54333899-28b07080-465f-11e9-8a6a-e36df51907f2.png)

**Comment by whDongRui** [comment]
* 全部应用列表中--应用服务商(admin登录)/开发者(ISV登录)，这个后端接口apps中增加了isv这个返回字段，这一列目前能显示出数据了。代码请见[PR](#921).

* 应用审核列表中-- 提交者(admin登录显示服务商/ISV登录显示开发者)，这个按讨论的方法也显示出数据了。代码请见[PR](#928).

* 全部应用 -- 应用详情 --  审核记录中审核人员中isv登录有的信息显示不出来，是因为isv查询用户数据的权限不够造成的，已按和Stark讨论的方案，查询用户时有user_id传参时安system权限来取数据了。
