### ISSUE TITLE
应用显示

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#904]
![image](https://user-images.githubusercontent.com/5114179/54334498-2ea75100-4661-11e9-8b5b-9529665d1184.png)

**Comment by whDongRui** [comment]
这个现在可以显示服务商的名称了，效果如下截图。 修复代码请参见[PR](#963)

<img width="1350" alt="图片" src="https://user-images.githubusercontent.com/38676269/54743228-86643000-4bfe-11e9-9d3d-9bfef1bc882b.png">
