### ISSUE TITLE
ISV : 查看应用详情 - 审核记录

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#915]
https://zpl.io/bJ9Eggr

最后一列需要带上审核人员的信息：
1）如果是 ISV 管理员（自己或其他有审核权限的管理员），需要显示用户名和邮箱
2）如果是平台审核阶段，就显示平台二字就可以

**Comment by whDongRui** [comment]
全部应用中现在查询的是已上架或已下架的数据，即查询的都是审核完成的数据。这个就不会存在还要处理的数据，下面设计图中有显示”开始处理“的按钮应该不存在。

<img width="806" alt="图片" src="https://user-images.githubusercontent.com/38676269/54522357-fc228e80-49a7-11e9-9cfd-fc03221e7f93.png">

目前的显示情况
<img width="737" alt="图片" src="https://user-images.githubusercontent.com/38676269/54522908-4eb07a80-49a9-11e9-8fb0-54a479d7400e.png">

**Comment by whDongRui** [comment]
目前应用审核已处理列表中已经按上面issue中描述的来显示了。代码请参见[PR](#944 )

<img width="1085" alt="图片" src="https://user-images.githubusercontent.com/38676269/54578176-aac2df80-4a39-11e9-9642-6f52be9f67d5.png">
