### ISSUE TITLE
节点列表的显示

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#916]
<img width="881" alt="屏幕快照 2019-03-14 下午4 54 08" src="https://user-images.githubusercontent.com/316145/54343474-d761aa80-4679-11e9-81cd-77c03f6cddbd.png">

既然节点没有名称，就把角色放到第一列，加粗显示，下面是 ID。目前这样空一行感觉像 bug

**Comment by whDongRui** [comment]
这个页面的样式今天已经修改了，修改后的效果如下截图。 代码请参见[PR](#957)

<img width="1277" alt="图片" src="https://user-images.githubusercontent.com/38676269/54681276-e7303180-4b46-11e9-9168-7408233fb229.png">
