### ISSUE TITLE
ISV入驻申请显示问题

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#917]
![image](https://user-images.githubusercontent.com/5114179/54345539-33c6c900-467e-11e9-8fd4-a635c8b06e05.png)

**Comment by whDongRui** [comment]
刚在本地已经修复了，现在的效果如下截图。并且之前这个地方的数据也有问题现在也修复了。

<img width="806" alt="图片" src="https://user-images.githubusercontent.com/38676269/54420372-ccc01780-4744-11e9-86b9-6c79c8a4ea24.png">
