### ISSUE TITLE
第一次创建应用的右侧配图

### ISSUE THREAD

**Issue by imdonkey** [openpitrix/dashboard#918]
https://zpl.io/adPwjLe

zeplin 上可以下载 svg 格式，用于各个分辨率下

**Comment by whDongRui** [comment]
这个页面的样式已修改，代码请参见[PR](#949)

<img width="1347" alt="图片" src="https://user-images.githubusercontent.com/38676269/54591630-998fc800-4a65-11e9-87c0-c312aa65fce7.png">
