### ISSUE TITLE
ISV：应用开发，应用显示不全

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#920]
![image](https://user-images.githubusercontent.com/5114179/54350166-bb650580-4687-11e9-9eac-764e47227b80.png)

**Comment by wangxhsoft** [comment]
![image](https://user-images.githubusercontent.com/5114179/54400724-33badd80-46ff-11e9-80a1-d832352e812e.png)

**Comment by whDongRui** [comment]
这个昨天晚上已经修复了，上午单机环境的代码可能没更新。修复代码请参见[PR](#921)
<img width="1345" alt="图片" src="https://user-images.githubusercontent.com/38676269/54411889-c1acbd80-472b-11e9-891a-bfaa72eabe9b.png">
