### ISSUE TITLE
AWS:网络标识

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#922]
![image](https://user-images.githubusercontent.com/5114179/54401815-44218700-4704-11e9-9c88-1ed5294baa6b.png)

**Comment by wangxhsoft** [comment]
哪个是外网，哪个是内网

**Comment by whDongRui** [comment]
这个上面数据取的是private ip, 下面取的是eip。 这个需要加提示吗？

**Comment by wangxhsoft** [comment]
加个图标，以示区分，要不看着不知道哪个是哪个

**Comment by whDongRui** [comment]
已经加了图标，并且加上了title提示，效果如下截图。代码请参见[PR](#961)

<img width="1254" alt="图片" src="https://user-images.githubusercontent.com/38676269/54735096-f9f64500-4bde-11e9-9444-b295af1e41a1.png">
