### ISSUE TITLE
nginx k8s部署成功，详情没有任何信息

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#924]
![image](https://user-images.githubusercontent.com/5114179/54403837-720ac980-470c-11e9-87eb-a7c87cbb3329.png)

**Comment by whDongRui** [comment]
这个Stark已经叫前端增加了传参with_detail = true，目前K8S的cluster详情已经能查到节点信息了。

<img width="1181" alt="图片" src="https://user-images.githubusercontent.com/38676269/54487767-931e1680-48d4-11e9-921a-1d9c7bca777a.png">

**Comment by iwisunny** [comment]
我看问题解决了，可以关闭issue
