### ISSUE TITLE
wordpress 下面的helm类型无法下架

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#925]
![image](https://user-images.githubusercontent.com/5114179/54404226-c06c9800-470d-11e9-9b3e-2846283b0e43.png)

**Comment by chilianyi** [comment]
![Screenshot from 2019-03-15 12-14-27](https://user-images.githubusercontent.com/5917832/54408193-eb5de880-471b-11e9-832b-9ff2ffed4b6d.png)
我看已经下架了，是怎么操作报无法下架呢。

**Comment by whDongRui** [comment]
@chilianyi 这两个是在我本地测试时下架了，上面你说的应该是代码没更新，现在代码应该已经发布到单机环境上去了。修复代码请参见[PR](#927)

<img width="1294" alt="图片" src="https://user-images.githubusercontent.com/38676269/54411765-33d0d280-472b-11e9-9603-1433c5c205f6.png">
