### ISSUE TITLE
user：显示问题

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#926]
![image](https://user-images.githubusercontent.com/5114179/54405436-88675400-4711-11e9-8879-c847565948d4.png)
![image](https://user-images.githubusercontent.com/5114179/54405504-cbc1c280-4711-11e9-8dcd-9d8a910a1ef0.png)
![image](https://user-images.githubusercontent.com/5114179/54405542-ef850880-4711-11e9-8f84-5557bb58f536.png)

1：应用信息
2：交付方式，没有显示出来
3：部署的是5.6，显示的是0.3，进去以后，也没有版本号信息，会让用户认为部署错了

**Comment by whDongRui** [comment]
Cluster相关的页面今天已经个性了，第一张截图中的版本信息先前取的是app中的信息，今天加了查询对应version信息了。代码请参见[PR](#957)

<img width="1325" alt="图片" src="https://user-images.githubusercontent.com/38676269/54681405-41c98d80-4b47-11e9-9c9b-d986d58f4ebc.png">

最后一张截图是因为查询cluster详情，没加with_detail = true, 这个后来后端叫加上了。现在有数据了。

<img width="1307" alt="图片" src="https://user-images.githubusercontent.com/38676269/54681561-aab10580-4b47-11e9-95f0-cf3486c6dd25.png">
