### ISSUE TITLE
查询用户实例，需要去掉limit=1

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#936]
![Screenshot from 2019-03-16 23-37-13](https://user-images.githubusercontent.com/5917832/54477688-f5c7d180-4844-11e9-918e-0d76f5e95147.png)

**Comment by whDongRui** [comment]
@chilianyi ，这里的第一个clusters接口只是为了查询本月部署次数，用的是返回结果中的total_count。之前不是建议查询总数时加上limit=1，这里确实要去掉这个传参那就是默认的limit=10了？

**Comment by whDongRui** [comment]
这里limit已经给去掉了，取的默认值为10

<img width="1210" alt="图片" src="https://user-images.githubusercontent.com/38676269/54591786-f2f7f700-4a65-11e9-99d5-1d9f02ef1d9e.png">
