### ISSUE TITLE
vmbased 修改环境变量

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#966]
![Screenshot from 2019-03-21 17-59-51](https://user-images.githubusercontent.com/5917832/54745182-e8736400-4c03-11e9-9426-f027de37df2d.png)

需要改成表单格式

![Screenshot from 2019-03-21 17-59-14](https://user-images.githubusercontent.com/5917832/54745218-f1643580-4c03-11e9-95e9-ff56d725b9ee.png)

**Comment by iwisunny** [comment]
api参考: https://tower.im/teams/637817/documents/5793/
