### ISSUE TITLE
“应用中心” 的页面，查询api需要加上owner参数  

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#970]
![Screenshot from 2019-03-21 19-54-16](https://user-images.githubusercontent.com/5917832/54750612-40fe2d80-4c13-11e9-9cd9-de6bef1cfc5e.png)

这样表面是查询自己创建的集群， 否则现在是列出了所有用户使用的。

**Comment by whDongRui** [comment]
好的，目前已经加上了owner参数。修复代码请参见[PR](#988)

<img width="1144" alt="图片" src="https://user-images.githubusercontent.com/38676269/54799228-4bfaa180-4c97-11e9-92f6-3478a07a07c5.png">
