### ISSUE TITLE
下架的版本，无法删除，应用也无法删除

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#981]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5114179/54796040-8eb57d00-4c89-11e9-8054-f00bcd03a758.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/5114179/54796055-9ecd5c80-4c89-11e9-8f30-97b348a83978.png">

**Comment by whDongRui** [comment]
这个已经修复了，目前可以让version有删除操作的状态控制为'draft', 'rejected', 'passed', 'suspended'。
下面截图的为已下架的版本，目前已经有了删除入口，修复代码请参见[PR](#988)

<img width="1280" alt="图片" src="https://user-images.githubusercontent.com/38676269/54799428-29b55380-4c98-11e9-92d7-ab8dc8bb3bc3.png">
