### ISSUE TITLE
isv：应用开发，状态不对

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#983]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/5114179/54797288-74ca6900-4c8e-11e9-8657-febcf08ec0b5.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5114179/54797296-7bf17700-4c8e-11e9-9776-a78e7ce864b2.png">

**Comment by whDongRui** [comment]
这个问题同[issue990](#990), 这个我先关掉了。
