### ISSUE TITLE
runtime 显示不对

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#987]
![image](https://user-images.githubusercontent.com/5114179/54798445-d4774300-4c93-11e9-9d0b-7677f3b758e4.png)
![image](https://user-images.githubusercontent.com/5114179/54798455-e48f2280-4c93-11e9-8133-ecd185320f5a.png)

**Comment by whDongRui** [comment]
这个是在切换交付类型时，查询runtimes没有传user_id导致的。已经修复了，代码请参见[PR](#988)
这个截图里面的versions没有传状态去过滤，在另外一个PR中已经解决了。

<img width="1190" alt="图片" src="https://user-images.githubusercontent.com/38676269/54801617-ad743d80-4ca2-11e9-930a-44a4ac264752.png">
