### ISSUE TITLE
应用状态不匹配

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#990]
![image](https://user-images.githubusercontent.com/5114179/54801039-f1b20e80-4c9f-11e9-82cf-36f7257e2f77.png)
![image](https://user-images.githubusercontent.com/5114179/54801045-f8d91c80-4c9f-11e9-8827-389eb47aae8b.png)

**Comment by whDongRui** [comment]
这里是有问题，目前导航中的app信息是从本地localstorage取的，在删除app，更新app状态进也要同步更新本地localstorage的app信息，这个我一会改一下。

**Comment by whDongRui** [comment]
这个已经修复了，修复代码请参见代码 [PR](#992)

**Comment by iwisunny** [comment]
solved by #992
