### ISSUE TITLE
应用已删除，导航没有更新

### ISSUE THREAD

**Issue by wangxhsoft** [openpitrix/dashboard#991]
![image](https://user-images.githubusercontent.com/5114179/54802779-bb788d00-4ca7-11e9-9754-b2cd6b0e32d3.png)
![image](https://user-images.githubusercontent.com/5114179/54802783-c29f9b00-4ca7-11e9-80e9-87174d530cac.png)

**Comment by whDongRui** [comment]
这个同issue990,已经修复了，修复代码请参见代码 [PR](#992)

**Comment by iwisunny** [comment]
solved by #992
