### ISSUE TITLE
SSH密钥 页面展示问题

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/dashboard#999]
![Screenshot from 2019-03-22 22-48-51](https://user-images.githubusercontent.com/5917832/54831112-baba1800-4cf4-11e9-90ed-ad7c33647030.png)

(0) 显示的是什么。 
目前通过名字看不出是什么， 最好能点击查看ssh秘钥内容。

**Comment by whDongRui** [comment]
好的，这个地方我问一下吕婷，看怎么样显示好。

**Comment by whDongRui** [comment]
@imdonkey , 目前ssh密钥的页面想查看ssh秘钥内容，没有界面显示这个内容。你看一下这部分内容怎么显示的好？

**Comment by imdonkey** [comment]
主要是想看到密钥结尾的邮箱么？

**Comment by whDongRui** [comment]
@chilianyi 密钥好像没有邮箱信息吧，应该是密钥的公钥内容吧，这个得问一下stark?

**Comment by chilianyi** [comment]
是的，公钥的内容吧。这个应该也不怕暴露。

**Comment by imdonkey** [comment]
@whDongRui 设计稿更新了 https://zpl.io/andEW0A

如果是在 ISV 或 Admin portal 中右侧新增部分的背景色就换成 N10，没有阴影，另外注意操作入口放到了右侧，同时左侧的数字统计内容变成了右对齐。

**Comment by whDongRui** [comment]
好的。我按这个设计稿改一下。

**Comment by whDongRui** [comment]
已经改了，修改代码请参见 #1088 

<img width="1237" alt="图片" src="https://user-images.githubusercontent.com/38676269/55226117-37964600-524f-11e9-8e47-f0cb7c946a65.png">
